### ISSUE TITLE
Switch to c++17 and remove Boost 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#106]
We need to get rid of SWIG before this step. 

After #55 
After #81

**Comment by dkeeney** [comment]
@breznak here is something for you to look into...
There are two Functors at the end of nupic/math/Utils.hpp
These don't compile on C++17 because std::unary_function<Pair...> is no longer supported.

Here is some code that seems to work under MSVC, C++17 but when I tried it on Ubuntu C++11 it would not compile.  Did not investigate further.  If you are looking for something to do can you look into this for me?  Don't need it until we switch to C++17.

```
  /**
   * This is a 'C++ function object' or Functor.  An object that can be passed
   * as if it were a C function. It is created by having a class containing an
   * overload of the () operator.
   * This replaces the std::unary_function<> which is not in C++17
   *
   * Function object that takes a single argument, a pair (or at least
   * a class with the same interface as pair), and returns the pair's
   * first argument.
   */
  template <typename Pair>
  struct select1st {
    inline const auto &operator()(Pair &x) const {
      return x.first;
    }
  };

  /**
   * This is a 'C++ function object' or Functor.  An object that can be passed
   * as if it were a C function. It is created by having a class containing an
   * overload of the () operator.
   * This replaces the std::unary_function<> which is not in C++17
   *
   * It is a Function object that takes a single argument,
   * a pair (or at least a class with the same interface as pair), and returns the
   * pair's second element.
   */
  template <class Pair> struct select2nd {
    inline const auto &operator()(const Pair &x) const {
      return x.second;
    };
  };
```

**Comment by breznak** [comment]
I'll try

> but when I tried it on Ubuntu C++11 it would not compile. 

So dows it fail on c++17, or 11? 
Functors normally work ok in gcc/clang, must be ill-formed or sth

**Comment by dkeeney** [comment]
It was failing on 11.
Let me stick it back in and try again.

**Comment by dkeeney** [comment]
Here is the error:
```
/home/dave/cpp/src/nupic/math/Utils.hpp:366:44: error: ‘operator()’ function uses ‘auto’ type specifier without trailing return type
     inline const auto &operator()(Pair &x) const {
                                            ^~~~~
/home/dave/cpp/src/nupic/math/Utils.hpp:366:44: note: deduced return type only available with -std=c++14 or -std=gnu++14
```
If I had read the entire error message it told me why.
So, I guess I will put some conditional compile around it and use the new one for C++14 or greater.

**Comment by breznak** [comment]
With #169 we'll have most of boost includes removed, 
only remaining are 
- [ ] math/ArrayAlgo.hpp
- [ ] math/Math.hpp

and I'm working on those. 

@dkeeney can we revisit switch to c++17 #55 and then proceed with this one?

**Comment by dkeeney** [comment]
Hmmm, I thought I already got rid of those....Oh,  The concept_check.  We can probably just delete that but perhaps someone thinks those are useful.
