### ISSUE TITLE
ARM64 support 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#131]
from https://github.com/numenta/nupic.core/issues/1439 

Check if we can build on Arm64 too. 
Should be easier, as ASM and platform specific code was mostly removed. 
- [ ] solve compiler differences
- [ ] possible cmake changes 
- [x] is there a free arm CI?  -> moved to #134 

Thanks for testing when you have time, @paulscode

**Comment by paulscode** [comment]
For ARM CI, you may be able to leverage Docker by adding the qemu-arm-static binary to the image.

`COPY qemu-arm-static /usr/bin`

Image will then run natively on ARM and emulate ARM with qemu on x86.

**Comment by breznak** [comment]
> For ARM CI, you may be able to leverage Docker by adding the qemu-arm-static binary to the image. 

That'd be cool! And by CI you're talking about Travis? I'll see if we can manage Linux as well as ARM CI under one account (?)

**Comment by breznak** [comment]
Thanks, we can run docker on Travis. It'll be really nice to have a separate CI running for this

**Comment by breznak** [comment]
Moving here discussion from https://github.com/htm-community/nupic.cpp/issues/134#issuecomment-485639982 

> [ 63%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/BasicTypeTest.cpp.o
/usr/local/src/nupic.cpp/src/test/unit/ntypes/BasicTypeTest.cpp:115:49: error: narrowing conversion of '-128' from 'int' to 'nupic::Byte {aka char}' inside { } [-Wnarrowing]
   Byte bufByte[8] = {0, 1, 2, 3, 4, 5, -128, 127};
 
> "char" is signed on x86 and x64, and unsigned on ARM. The error refers to the fact that the compiler is being told to convert int 128 to a signed char.

- a simple fix would be to add a specific cast `static_cast<Byte>(-128)` which would stay unchanged on x86, and underflow intentionally on arm. 

Fixing this type of errors should be relatively easy, as we define and use our types in `types/Types.hpp`, so we could use #ifdef to change for ARM. 

Specifically about byte (from above Types.hpp): 
```
/**
* Represents a signed 8-bit byte.
* (note that std::byte is unsigned char.)
*/
#ifdef Byte
#undef Byte
#endif
typedef char Byte;
```

@dkeeney we've discussed this, we do we need a signed byte? Ideally cross-platform would be std::byte.

**Comment by dkeeney** [comment]
> do we need a signed byte? Ideally cross-platform would be std::byte.

As far as I know it has always been a signed char.  I have no reason for making it signed.  But if we change it to unsigned then we may need to add some casts (or maybe remove some) in the places it is used.  Personally I would prefer the unsigned char (std::byte) as being a Byte.
