### ISSUE TITLE
Find CI for ARM64 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#134]
https://github.com/htm-community/nupic.cpp/issues/131#issuecomment-442911522

**Comment by breznak** [comment]
https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

**Comment by brev** [comment]
(Parsed the articles linked above):

* Use QEMU emulation.
    * Plain Linux ([first article](https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html)): Use `chroot`. Or,
    * Docker ([second article](https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/)): Use qemu docker image.
* The bad news = very slow builds and tests (emulation).

**Comment by breznak** [comment]
> Docker (second article): Use special qemu docker image mentioned in article.

thanks, I'm inclining to the Docker solution. Do you have some experience compiling HTM on ARM platform?

**Comment by brev** [comment]
Hi @breznak, I bet I'm dangerous enough to at least get us started. I tend to work slow and asynchronous, so if that's cool, I'm game. Could you point me to where the builds are done currently?  I guess I'd need a login too.  thx.

**Comment by breznak** [comment]
>  I'm game 

great! :+1: 

the linux CI runs on Travis, 
https://travis-ci.org/htm-community/nupic.cpp

the CI files are in 
`.travis.yml` (different of other CIs) 

I think ARM64 should be considered as a separate platform, so separately running CI. So you can choose a provider of your choice (Travis, CircleCI,..?). I think the Docker solution should be the easiest. 

As of running the CI, if you fork this repo, and make a PR, the CI will pick-up the changes in the configuration `yml` file and run as instrumented.

**Comment by brev** [comment]
sounds great, thanks.

**Comment by brev** [comment]
Hi @breznak 
I've got an arm64 docker build starting on my local box via Circle CI, and gotten to my first compile failure.  Please see changes (so far) here:
https://github.com/brev/nupic.cpp/pull/1
I'm stuck here for the moment until I can dig in on the error more.

Also, is #131 a duplicate? 

thanks!

**Comment by brev** [comment]
For ease, here is the error (from https://github.com/brev/nupic.cpp/pull/1):
```
[ 63%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/BasicTypeTest.cpp.o
/usr/local/src/nupic.cpp/src/test/unit/ntypes/BasicTypeTest.cpp:115:49: error: narrowing conversion of '-128' from 'int' to 'nupic::Byte {aka char}' inside { } [-Wnarrowing]
   Byte bufByte[8] = {0, 1, 2, 3, 4, 5, -128, 127};
```

Doing some searching, I [found a discussion](https://github.com/dart-lang/sdk/issues/8807#issuecomment-108353689) that mentions this:
```
"char" is signed on x86 and x64, and unsigned on ARM. The error refers to the fact that the compiler is being told to convert int 128 to a signed char.
```

In the above link, there is a link to a patch. It may contain the kind of changes that might be necessary to fix this cross-platform:
https://storage.googleapis.com/google-code-attachments/dart/issue-8807/comment-7/unsigned_char.patch

Let me know what you think, thanks.

**Comment by breznak** [comment]
> I've got an arm64 docker build starting on my local box via Circle CI, and gotten to my first compile failure. 

this is a great progress, thanks @brev ! I've reviewed your PR, please open a PR to this repo, I'd like to merge the functionality as is, and fix the errors separately. 

> Also, is #131 a duplicate?

sort of now, this issue was about deciding on the ARM CI (you chose circleCI) and making it run,
and 131 is about the actuall build compatibility, which you've started and we'll do next.

**Comment by brev** [comment]
Tracking here now:
https://github.com/htm-community/nupic.cpp/pull/430

**Comment by breznak** [comment]
Fixed, thank you!
