### ISSUE TITLE
Missing functions that have Python bindings.

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#145]
I have found the following that have python bindings that were removed from the library.
In py_Random.cpp
- getUInt64(max=MAX64)
- constant MAX64
- sample<UINT32>()

Are we going to provide an alternative or do we assume no .py code calls these?

**Comment by breznak** [comment]
To justify why it was removed and why I’d recommend removal from py: 
- simpler implementation and speed reasons 
- 64 had never been used in cpp codebase 
- main use of Random is generating random index of columns, which means 0..2048 range. There 32bit int is more than enough 
- just multiply 2 ints if you needed 64b occasionally

**Comment by dkeeney** [comment]
The bindings contained both 32bit and 64bit.  So both are exposed to .py
code.  I vote that we just remove the bindings for the 64bit random and if
we find that there is .py code that uses it we can build the 64bit
version.  use two 32bit values and shift and AND one of them to get 64bits.

**Comment by breznak** [comment]
Closing this for now, as resolved in #147 . If needed again, please reopen.
