### ISSUE TITLE
Remove SP.synPermTrimThreshold

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#150]
Reason: Connections module does not support this, blocks issue #93 

Impact: This has public setter/getters but I suspect that they exist to allow testing.

I don't understand why this mechanism exists.  It moves the valid range of permanences from [0, max] to [trim, max].  If the SP is going to trim synapses, it should trim at zero.  Given time, synapses can reach zero via the adaptSynapses method, trimming at a higher threshold just changes the lower bound.

**Comment by ctrl-z-9000-times** [comment]
From https://discourse.numenta.org/t/spatial-pooling/2172
> **Permanence Trimming**
> Theoretically, every column has a permanence value associated with every input bit in its potential pool. Practically though, many of the permanence values are extremely small. To reduce the memory footprint of the spatial pooler, permanence values below a certain threshold are zero’ed out. This is referred to as trimming.

The connections class can not do this optimization because it keeps its potential pool data and its permanence data in the same struct.  I don't think that the memory impact will be too significant.  In the connections class, each potential synapse take 28 bytes of RAM (i think).

**Comment by ctrl-z-9000-times** [comment]
I did a search through the following repositories for the keywords: `setSynPermTrimThreshold` & `getSynPermTrimThreshold`
* numenta/nupic.core - only used by SP
* numenta/nupic - only used by SP
* numenta/htmresearch - not found
* numneta/htmresearch-core - not found
* numenta/nupic.vision - not found
* numenta/htmpapers  - not found
* numenta/nupic.regression - not found
* numenta/numenta-apps - not found
* numenta/nupic.geospatial - not found
* numenta/nupic.rogue - not found

**Comment by breznak** [comment]
> I did a search through the following repositories for the keywords 

Thanks, but I'm not so worried about breaking the API (it's a minor change and should have been private anyway), but about the functionality. 

>> Practically though, many of the permanence values are extremely small. To reduce the memory footprint of the spatial pooler, permanence values below a certain threshold are zero’ed out. This is referred to as trimming. 

> I don't think that the memory impact will be too significant. In the connections class, each potential synapse take (EDIT) 20 bytes of RAM. 

- So memory-wise, this is an OK; 
- conceptually OK (ideally better w/o trimming)
- last, I want to discuss performance?:  permanences cannot be sparse anyway, right (or unlikely, all perm should be used)? Can we still keep as sparse the active cols, etc..

> The connections class can not do this optimization because it keeps its potential pool data and its permanence data in the same struct. 

Well, there could be method that goes through all permanences in the pool and crops the below stimilus to the threshold, right? But as above, probably not needed and maybe even better w/o that (fake) functionality

**Comment by breznak** [comment]
Implemented in #151
