### ISSUE TITLE
Pybind: modules not loading, tests don't run in Debug mode

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#167]
After #157 , 
- linux runs ok
- OSX does not load py modules

**Comment by dkeeney** [comment]
I have access to a MAC but it does not have a development environment on it.  Don't know my way around a Mac very well but maybe I can figure out how to set this up. No promises.

**Comment by breznak** [comment]
> I have access to a MAC  

:+1:  
Numenta devs run on OSX, so there are readmes how to install and setup. 
Basically you can follow what we do in `circleci.yml` to get it up and running... 

I can try in a VM, but it's very slow.

**Comment by dkeeney** [comment]
I have to go get my hair cut.  When I get back I will start work on it.

**Comment by dkeeney** [comment]
Things I have noticed so far:

- I am building with XCode 9.1.0.  The latest compiler is XCode 10.1    CircleCI is using XCode 9.0.1.

- When this links with the boost library that it built, it warns about being compiled for a newer OSx.  Don't know if that matters.

- Also noticed that circle is doing a debug build.  Should not matter.

- It compiles fine with cmake.  But with `python setup.py install --user` it rebuilds yaml-cpp.  And this time it errors with `string.h not found` (from <cstring.h> in yaml-cpp)   These are the C functions not the C++ ones.

I did notice that yaml-cpp was being recompiled on circleCI but at least it did not fail there.
If I clear the cmake cache and just run `python setup.py install --user` without first running cmake, I get a release build.

Oh, and the release build errors out on an unused variable idx in line 221 of the new Sdr.hpp.

**Comment by dkeeney** [comment]
@ctrl-z-9000-times  in Sdr.hpp line 200 and again in line 221 you have the following:
```
        for(auto idx : flatSparse) {
            NTA_ASSERT(idx < size);
        }
```
When compiling for Release, the NTA_ASSERT() macro compiles to nothing.
This results in the CircleCI build to error on `unused variable idx` because idx is no longer used.

Not sure of your intent in this case.  
 - If you want the release build to not do the check then an `#ifdef NTA_ASSERTIONS_ON` should be around the entire loop.
- If the intent is for the check to always be made then use the macro NTA_CHECK() which always compiles.

The CircleCI normally compiles in Debug mode so these ASSERT's are made during unit tests.  The Travis build is in Release mode so the ASSERT's are ignored.

Since this is not really related to this PR, can you make this change for me in an appropriate PR?  
Thanks.

**Comment by breznak** [comment]
>  And this time it errors with string.h not found (from <cstring.h> in yaml-cpp) These are the C functions not the C++ ones. 

This is odd, but I'd say unrelated to the CI issue (?) 

There are some changes in yaml-cpp that might be useful: 
https://github.com/jbeder/yaml-cpp/compare/yaml-cpp-0.6.2...master
Do you want to install from commit, to set it to master? (and not release) If yes, that would be a separate small PR, please. 

So in Relase your OSX compiles and tests fine, including the python modules?

**Comment by dkeeney** [comment]
Good morning.

>So in Relase your OSX compiles and tests fine, including the python modules?

No, on OSX, Release mode will not compile due to the unused variables in Sdr.cpp.

**Comment by breznak** [comment]
> No, on OSX, Release mode will not compile due to the unused variables in Sdr.cpp.

I mean appart from that. Or you haven't tried yet? Now the change is in master, so please let us know... 

If it was the case, a "hack" would be to switch OSX CI to Release and Linux to Debug, or both..Not a proper way, but it would pass

**Comment by dkeeney** [comment]
My Mac decided it wants to do OS updates so I will have to wait until these are done.

**Comment by dkeeney** [comment]
Some interesting results:
OSX, Release mode.  C++ unit tests fail
```
[==========] 340 tests from 46 test cases ran. (32545 ms total)
[  PASSED  ] 337 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] ConnectionsPerformanceTest.testTM
[  FAILED  ] ConnectionsPerformanceTest.testTMLarge
[  FAILED  ] ConnectionsPerformanceTest.testSP
```

Maybe it is just my machine:   Mac Air, I7 2012
```
[----------] 4 tests from ConnectionsPerformanceTest
[ RUN      ] ConnectionsPerformanceTest.testTM
0.00247646 in temporal memory: initialize
1.0738 in temporal memory: initialize + learn
1.29747 in temporal memory: initialize + learn + test
/Users/dave/cpp/nupic.cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:269: Failure
Expected: (tim) <= (1.0*Timer::getSpeed()), actual: 1.29749 vs 1.20603
[  FAILED  ] ConnectionsPerformanceTest.testTM (2516 ms)
[ RUN      ] ConnectionsPerformanceTest.testTMLarge
0.00524312 in temporal memory (large): initialize
1.90551 in temporal memory (large): initialize + learn
2.33452 in temporal memory (large): initialize + learn + test
/Users/dave/cpp/nupic.cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:277: Failure
Expected: (tim) <= (1.9*Timer::getSpeed()), actual: 2.33455 vs 2.29146
[  FAILED  ] ConnectionsPerformanceTest.testTMLarge (2335 ms)
[ RUN      ] ConnectionsPerformanceTest.testSP
0.508757 in spatial pooler: initialize
6.72745 in spatial pooler: initialize + learn
6.80807 in spatial pooler: initialize + learn + test
/Users/dave/cpp/nupic.cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:288: Failure
Expected: (tim) <= (5.3*Timer::getSpeed()), actual: 6.80809 vs 6.39196
[  FAILED  ] ConnectionsPerformanceTest.testSP (6822 ms)
```

**Comment by dkeeney** [comment]
The .py tests do succeed.
```
153 passed, 30 skipped in 3.65 seconds 
```

**Comment by breznak** [comment]
> [  FAILED  ] ConnectionsPerformanceTest.testTM
[  FAILED  ] ConnectionsPerformanceTest.testTMLarge
[  FAILED  ] ConnectionsPerformanceTest.testSP
 

yes, you can ignore those. It's the check if the tests run fast enough. It will never be accurate for all machines. Just means your Mac is slower than the CI OSX. 

> The .py tests do succeed. 

Good news :+1: , and bad news. So we pass locally...and CI is somehow screwed.

**Comment by dkeeney** [comment]
Ubuntu, in Debug mode.  C++ unit tests are taking forever.  Will let you know if it passes when/if it ever finishes.

**Comment by dkeeney** [comment]
On OSX, Debug mode, it does fail the same way it does in CI.

**Comment by dkeeney** [comment]
So, it is not just CI.

I have to take a break.  Will be back in about an hr.

**Comment by breznak** [comment]
> On OSX, Debug mode, it does fail the same way it does in CI. 

Great success, we can reproducibly fail! So now we'll fix it. Thanks a lot!

**Comment by breznak** [comment]
I'm able to reproduce this on Linux in Debug mode! 

> ImportError while importing test module '/mnt/store/devel/HTM/htm-community/nupic.cpp/bindings/py/tests/algorithms/cells4_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
algorithms/cells4_test.py:31: in <module>
    from nupic.bindings.math import Random
E   ImportError: /mnt/store/devel/HTM/htm-community/nupic.cpp/build/Release/distr/src/nupic/bindings/math.so: undefined symbol: _ZN5nupic6Random5MAX32E

I'm suspecting: 
- some compile flag, include is set only for Release
- some ifdef-d includes? 
- can you review the py_Random module is OK, and that it exposes MAX32 properly, please?

**Comment by dkeeney** [comment]
I did check out the MAX32 property.  It's returned using a lambda function.  I don't see anything wrong with it.  Certainly nothing that would work with Release but not with Debug.

**Comment by dkeeney** [comment]
My Ubutntu Release mode unit_test run is still running.  
```
[----------] 4 tests from ConnectionsPerformanceTest
[ RUN      ] ConnectionsPerformanceTest.testTM
0.00826521 in temporal memory: initialize
0.479576 in temporal memory: initialize + learn
0.564217 in temporal memory: initialize + learn + test
[       OK ] ConnectionsPerformanceTest.testTM (4798 ms)
[ RUN      ] ConnectionsPerformanceTest.testTMLarge
0.0112118 in temporal memory (large): initialize
1.15168 in temporal memory (large): initialize + learn
1.33337 in temporal memory (large): initialize + learn + test
[       OK ] ConnectionsPerformanceTest.testTMLarge (1339 ms)
[ RUN      ] ConnectionsPerformanceTest.testSP
2.66154 in spatial pooler: initialize
1237.9 in spatial pooler: initialize + learn
1242.59 in spatial pooler: initialize + learn + test
[       OK ] ConnectionsPerformanceTest.testSP (1242598 ms)
[ RUN      ] ConnectionsPerformanceTest.testTP
19.8372 in temporal pooler: initialize
```
This is a BIG machine.  CPU: Intel i7-8700K 3.7Ghz 6-core Processor, 32Gb Ram.

I think your algorithm for determining iterations may need to be adjusted. But for Debug mode, performance has little meaning.  Perhaps you should just set it for 1 iteration if running in Debug mode.

**Comment by dkeeney** [comment]
That TP performance test finally finished (after 47 min).  This thing has a very aggressive burst mode so for short a duration it goes way above 3.7Ghz. Perhaps that is what messed up the speed evaluation.
```
[ RUN      ] ConnectionsPerformanceTest.testTP
19.8372 in temporal pooler: initialize
2818.73 in temporal pooler: initialize + learn
2823.61 in temporal pooler: initialize + learn + test
[       OK ] ConnectionsPerformanceTest.testTP (2823639 ms)
```

And then it core dumped in the CppRegionTest.
```
[ RUN      ] CppRegionTest.testCppLinkingFanIn
Segmentation fault (core dumped)
```

**Comment by breznak** [comment]
> [       OK ] ConnectionsPerformanceTest.testSP (1242598 ms)
[ RUN      ] ConnectionsPerformanceTest.testTP
19.8372 in temporal pooler: initialize
This is a BIG machine. CPU: Intel i7-8700K 3.7Ghz 6-core Processor, 32Gb Ram.
I think your algorithm for determining iterations may need to be adjusted.  

This must be some bug, in Release, these test take ~30s altogether on my notebook. 

My report: 
Release: c++ tests OK, py OK
Debug: c++ N/A (testing now), py fail with the CI MAX32 err

**Comment by dkeeney** [comment]
This is a Debug build in Linux.  Running the **C++ tests** is where I get the very long test durations.
Yes, I get the MAX32 error when running the .py test 

I am still studying this but I suspect that `python setup.py install --user` needs some way to tell it that its a debug build.

**Comment by breznak** [comment]
> needs some way to tell it that its a debug build.

Should it? It should get all its c flags from cmake

-- 
Marek Otahal :o)

**Comment by dkeeney** [comment]
Within the setup itself it does some things (outside cmake).
Some docs say do this:
```
CFLAGS="-O0 -g" CXXFLAGS="-O0 -g" python setup.py install
```
But I don't think it is that simple in our case.

**Comment by breznak** [comment]
-g flag is debug mode, it would have been passed from cmake

-- 
Marek Otahal :o)

**Comment by dkeeney** [comment]
Inside setup.py, we call distutil function setup()
One of the arguments is:
```
    # This distribution contains platform-specific C++ libraries, but they are not
    # built with distutils. So we must create a dummy Extension object so when we
    # create a binary file it knows to make it platform-specific.
    ext_modules=[Extension('nupic.dummy', sources = ['dummy.c'])],
```
According to the Python documentation an externally compiled library cannot be loaded directly. So it must compile this dummy.c so that the linker can then pull in the library.  Its this part that needs to know its in debug mode.  Still trying to understand how this works and where to add the debug flags.

**Comment by dkeeney** [comment]
I am not making much progress on this.

I did find a way to pass compile arguments into the setup() function that builds the dummy.c extension. But unfortunately it just appends them to the end of the command so they are treated like more modules.  But it does not matter... It does know its debug.  Here is the command line:
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c dummy.c -o build/temp.linux-x86_64-2.7/dummy.o 
```
So that seems to be a dead-end.

**Comment by breznak** [comment]
> But it does not matter... It does know its debug. Here is the command line:

 End of line is good, command flags are overriden by the latest, so the last one matters. 
That means that setup's cmd matches Debug when c++ uses Debug? And we still fail? :( 

> -DNDEBUG -g  

this does not seem right, it says NotDEBUG and right after is debug flag

**Comment by breznak** [comment]
worst case, we build the c++ in Debug only for tests, then again in Release and make the bindings.

**Comment by dkeeney** [comment]
Let me summarize what we do know.
- The extension cannot load when it is compiled in debug mode.  Happens on any platform, not just the MacOS.
- The symbol displayed in the error `nupic.Random.MAX32` just happens to be the first one to be loaded. So it is likely that nothing is loading.
- I have verified that this symbol does exist in math.so.
- Any reference to domain nupic.bindings.xxx will execute the import_helper in `nupic/bindings/__init__.py`. This will (should) read the contents of the shared library into sys.modules where it can be accessed with an import.
- Putting debug displays inside `nupic/bindings/__init__.py` I see that nupic.bindings.algorithms and nupic.bindings.engine_internal do load successfully.  It only errors on nupic.bindings.math.

So, chasing the debug flags was probably a red herring.

**Comment by dkeeney** [comment]
Found the problem.
There were two instances of nupic::Random::MAX32.  I was looking at the wrong one!!
 The other one was in the default argument for the `getUInt32()` function.  The macro was expecting a constant, not a reference to a static property.  When I changed this to a constant value it all loaded.

There is another .py unit tests that failed:  Marked it as skipped.
- `network_test.py::NetworkTest::testSimpleTwoRegionNetworkIntrospection Segmentation fault (core dumped)`

**Comment by breznak** [comment]
Hurray! :tada: :clap: 

> The macro was expecting a constant, not a reference to a static property. When I changed this to a constant value it all loaded. 

I wonder..what kind of a devil's deal did you have to sign to figure this one out! :open_mouth: :+1:

**Comment by dkeeney** [comment]
Like I often do...if I am not making progress after a while, stop and re-evaluate the situation.  Look for some other way to tackle the problem.  In this problem I had to do that three times. I am glad it worked.
