### ISSUE TITLE
Proposed structural changes

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#199]
With the objective of reducing coupling between the algorithms and the Network Framework, I propose that we move source files around a little such that it is clear which modules are in which category.

- The algorithms category is code that is in algorithms/*, encoders/* and math/*.  Ideally we do not want algorithms code to be dependent on any of the Network Framework code.  
- The engine/* is part of the Network Framework.
- The regions/* code would be part of the framework but of course it must call algorithms in order to execute them so there is a dependency there.  We should try to avoid using algorithm code for what is a structural function.
- The os/* code is shared.

- The suggestion by @ctrl-z-9000-times 
```
    Move all of the supporting code for the core algorithms & encoders to utils.
        types/Serializable.hpp -> utils
        types/Types.hpp -> utils
        types/Exception.hpp -> utils
        ntypes/Sdr -> utils
        types/Fraction.hpp -> utils ... Maybe, its not used but I think it could be useful to keep with the utils
    Move all of data types for the engine to types.
        ntypes/* -> types
```
- I suggest moving Watcher.* -> types or engine
- Then ntypes folder goes away.
- Shared code are
-- os/*
-- Types.hpp
-- LoggingException.*, Log.hpp, and LogItem.* 
-- StringUtils.hpp
-- Serializable.hpp
-- Array must reference SDR or SDR must reference Array.

**Comment by breznak** [comment]
I don't know, I see your point, but my worry is that we (unnecessarilly) diverge too much from the numenta's repo. 
- What actuall improvement does this change bring? 
- It is harder for people coming from / reading manuals, docs on numenta to orient themselves in our repo. 
So far I'm inclining :-1: , you?

**Comment by dkeeney** [comment]
I see your point.
Perhaps just documenting which source files belong to which camp would be sufficient.

**Comment by breznak** [comment]
> Perhaps just documenting which source files belong to which camp would be sufficient. 

- Either :+1: 
- namespaces (just a thought)? 
- the #183 would fix this, wouldn't it?

**Comment by dkeeney** [comment]
> the #183 would fix this, wouldn't it?

Yes, that was the intent of #183 but that is a rather traumatic change.

**Comment by dkeeney** [comment]
I don't think this is going to happen so closing this issue.
