### ISSUE TITLE
Modular repo structure

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#2]
How to make the repos more modular for rapid development...

https://discourse.numenta.org/t/re-organisation-of-the-c-py-community-repos/ 

And old issue in nupic.core

**Comment by mattheiler** [comment]
Can we get a design document for this?
A bit more detailed in the forum topic, but...
For module design, I'd propose:

```
nupic.core    // -> [] C++ core
nupic.core.cs // -> [nupic.core] C++ core bindings
nupic.core.py // -> [nupic.core] C++ core bindings
nupic         // -> [nupic.core] C++ client 
nupic.cs      // -> [nupic.core, nupic.core.cs] C# client 
nupic.py      // -> [nupic.core, nupic.core.py] Python client
```

**Comment by breznak** [comment]
I'm for a more specialized/isolated repo structure! 
...will talk more in the forum

**Comment by breznak** [comment]
I'm considering this successfully finished! 
Thanks to @dkeeney 's porting to pybind and introduction of modules/bindings :+1: 

We now support: 
- [x] cmake downloads and configures external dependencies
- [x] hierarchical cmake files (standalone, if for src/, tests/, bindings/py/, external/) 
- [x] separation of (language) bindings into optional modules (bindings/py)
