### ISSUE TITLE
Math.hpp cleanup

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#213]
math/math.hpp
unary_function and binary_function are no longer in the standard for C++17.  They are just structures that make a few typedefs.
```
// TODO: Go through this file and fix all references to these two structs
//       and fix the code so they are not needed.
//       https://stackoverflow.com/questions/33114656/replacement-for-binary-function
```

**Comment by breznak** [comment]
If #169 is merged, it completely purges Math.hpp, that would resolve this.
