### ISSUE TITLE
remove nupic/types/ptr_types.hpp

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#219]
related #66 

```
  typedef std::shared_ptr<Link> Link_Ptr_t;
```

use the shared_ptr where needed, it's more obvious, this file is very small.

**Comment by dkeeney** [comment]
The Link_Ptr_t, Region_Ptr_t are used a lot but I think you are right it is more obvious if we actually say std::shared_ptr< >.  I will go ahead and do this.
