### ISSUE TITLE
TM testExtraActive randomly fails

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#240]
Bug introduced by PR #180 

Occasionally, this test randomly fails.   I added this test, my bad.  This tests uses random numbers and has no seed, it self seeds from system time.  I want to investigate why this fails, but a quick fix might be to use a hardcoded known-good random seed.

File: src/test/unit/algorithms/TemporalMemoryTest.cpp
`TEST(TemporalMemoryTest, testExtraActive) {`

**Comment by breznak** [comment]
> but a quick fix might be to use a hardcoded known-good random seed. 

For a CI test, I'd go with this solution

**Comment by ctrl-z-9000-times** [comment]
Should be fixed in PR #269
