### ISSUE TITLE
Connections::raisePermanencesToThreshold check for not enough synapses

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#246]
C++ Connections class method raisePermanencesToThreshold needs a check to makes sure that there are enough synapses.   Although the code looks safe, in debug mode there are a lot of extra checks which will notice that issue.  This line can increment an iterator beyond the end of it's array:
`auto minPermSynPtr = synapses.begin() + segmentThreshold - 1;`

Instead of incrementing this iterator beyond the end, it should max-out at the end of the array.

- [ ] Implement check
- [ ] Unit test

**Comment by breznak** [comment]
+1
I think this is the issue I had crash on me in mnist

-- 
Marek Otahal :o)

**Comment by breznak** [comment]
I found a "fix" for the bug, 
https://github.com/htm-community/nupic.cpp/pull/242#discussion_r255293237 

> auto minPermSynPtr = synapses.begin() + segmentThreshold - 1; 

The bug is not directly at that line, but above, 
- There can be situation (wrong?) SP settings, ... when Segment returns an empty synapses. 
`synapses.size() == 0`
    - should such Segment not exist in the first place?
    - if it can exist, we can just return early if segment is empty.
