### ISSUE TITLE
invalid free error in log, Release mode

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#250]
Only happens in Release mode, linux.

I have an idea about why this happens, and an idea for how to fix it.  I will probably submit a PR tonight or tomorrow.

**Comment by ctrl-z-9000-times** [comment]
I can't seem to reproduce this issue.

**Comment by dkeeney** [comment]
It can be caused by a pointer that is capitulated into more than one shared_ptr at the same time. I have tried to be very careful that does not happen but I may have missed something.

I ran the unit_tests, release mode on my Ubuntu 18 and did not see the problem either.

**Comment by breznak** [comment]
Closing, please reopen if happens again or if needed.
