### ISSUE TITLE
Switch to Python 3 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#26]
https://discourse.numenta.org/t/proposal-to-introduce-pybind-for-move-toward-python-3-compatibility/3110/65

- [x] use pybind11 lib in nupic.cpp
- [x] rewrite Py to python3 code

**Comment by breznak** [comment]
Ia this fixed in #212 ?

**Comment by ctrl-z-9000-times** [comment]
I think so.  Python 2 and 3 are both generated from the same pybind11 stuff, with out errors.

Python as a whole (2&3) needs work though (missing classes, more tests...)

**Comment by breznak** [comment]
Fixed.
