### ISSUE TITLE
TP, BacktrackingTM execution times depends on (SP's) input size, and should not

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#267]
I came to this issue in #265 , 

it affects only the old `TemporalPooler (Cells4) and derived BacktrackingTM`, TM (Connections) is unaffected. 

Issue: 
TP execution time depends on (SP) input size (after crossing some threshold) 

Replicable: always
run hotgym benchmark, observe TP's time for input size (10k, default), and 100k! 

Expected behavior: TP's time (same as TM's) does not depend on SP input size (depends on #cells, #columns, ...)

**Comment by breznak** [comment]
Another point for removing Cells4, rewriting TP, BackTM to use Connections #95 

The issue does not scale linerarily (see 10k->20k vs ->100k), so I suspect some memory corruption? Or a cache/stack collisions and less effective execution on HW? 

my benchmark 
```
[ RUN      ] HelloSPTPTest.performance
starting test. DIM_INPUT=10000, DIM=2048, CELLS=10
EPOCHS = 5000
INFO:   SP (l) local inhibition is slow, so we reduce its data 10x smaller
INFO:   Random seed: 2004968966
starting:  5000 iterations.Epoch = 4999
Anomaly = 0.999023
SP= 1101,1103,1104,1105,1106,1110,1114,1115,1116,1121
TP= 1101,1103,1104,1105,1106,1110,1114,1115,1116,1121
==============TIMERS============
Init:   0.174334
Random: 0.000665708
Encode: 0.0227264
SP (l): 1.03912(x10)
SP (g): 0.813722
TP:     2.21586
TM:     0.987252
BackTM: 1.81149
AN:     1.18997
AN:     1.65866
Total elapsed time = 9 seconds


from input 10k -> 20k == no change in TP times = OK


[ RUN      ] HelloSPTPTest.performance
starting test. DIM_INPUT=20000, DIM=2048, CELLS=10
EPOCHS = 5000
INFO:   SP (l) local inhibition is slow, so we reduce its data 10x smaller
INFO:   Random seed: 2506003449
starting:  5000 iterations.Epoch = 4999
Anomaly = 0.999023
SP= 1498,1499,1500,1501,1503,1504,1505,1506,1507,1511
TP= 1498,1499,1500,1501,1503,1504,1505,1506,1507,1511
==============TIMERS============
Init:   0.239623
Random: 0.000726215
Encode: 0.0472686
SP (l): 1.52722(x10)
SP (g): 1.07482
TP:     2.15721
TM:     0.994224
BackTM: 1.71091
AN:     1.27227
AN:     1.72048
Total elapsed time = 10 seconds



but changing input -> 100k, the TP/BackTM times increase! 
(those rely on SP.output, so #columns, and should in no way interact with the lower layer (SP, Input)) 

[ RUN      ] HelloSPTPTest.performance
starting test. DIM_INPUT=100000, DIM=2048, CELLS=10
EPOCHS = 5000
INFO:   SP (l) local inhibition is slow, so we reduce its data 10x smaller
INFO:   Random seed: 468026591
starting:  5000 iterations.Epoch = 4999
Anomaly = 0.999023
SP= 1,7,218,913,1038,1773,1774,1775,1812,1925
TP= 1,7,218,913,1038,1773,1774,1775,1812,1925
==============TIMERS============
Init:   0.78024
Random: 0.000998926
Encode: 0.244995
SP (l): 4.96727(x10)
SP (g): 2.57839
TP:     14.8721
TM:     1.05083
BackTM: 11.6211
AN:     2.19536
AN:     2.6707
Total elapsed time = 40 seconds



Summary: same task, only changing SP's input size (10k, 20k, 100k) TP's execution differs!! 
TP:     2.21586,  2.15721,  14.8721

```

**Comment by ctrl-z-9000-times** [comment]
> Or a cache collisions and less effective execution on HW?

Very plausible.

> rewriting TP

I'm current researching this task, except it's called the CP now and it does a few extra things.

**Comment by breznak** [comment]
The PR fails as the test is known to fail now. 

- we should test this with `valgrind --cachegrind` to validate the issue is caused by suboptimal caching for such large data. 
- how to improve the above? 
  - more size-compact SDRs
  - compile flags to better hint cache use? 
  - apparently SP has too much of data for the cache, so it cannot be effective. TP still could. 

- counter argument for it being caused by cache only: 
 - TM(conn) still performs well (under same conditions = cache used by SP) 

Moved from https://github.com/htm-community/nupic.cpp/pull/268#issuecomment-462826623
