### ISSUE TITLE
What is a dimension and why do we need it?

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#273]
I would like to have a better understanding of how dimensions are used and what they are.
- Is a dimension a coding trick to generate faster code in an algorithm?
- Is a dimension a position within the minicolumn and therefore distances from that coordinate mean something?
- How does a user determine what a dimension should be?
- Could dimensions be programmatically generated?
- What happens to dimensions in a Fan-In condition where an input has more than one output connected?
- Can a dimensions be propagated from one output to the input of the next region or regions and what does it mean if the dimensions are different?

**Comment by breznak** [comment]
>...  do we need [dimensions] to be set outside of an algorithm.

> What I wanted to do was allow a user to set dimensions on a region anyway. That value would be placed in the SDR when the Link creates the output SDR. The dimensions on an input SDR would be determined by the output to which it is connected.

I think dimensions of a region (in/out) should match the dims of its algorithm, so the region should not (have to be able to) set dimensions on its own, just obtain it from the internal algo. 

> Is a dimension a coding trick to generate faster code in an algorithm?

no, not only. Though implementation for 1D tend(ed?) to be faster. 

> Is a dimension a position within the minicolumn and therefore distances from that coordinate mean something?

Yes, dimension is related to topology of the minicolumns, good example is Hotgym (1D topology for numbers) vs MNIST (where 2D topology naturally aligns with the raw image data) 
In fact, the only part able to change topology is SP (dims(input) -> dims(columns)), all other copy SP's dim(columns) and don't alter that. (Encoder, Anomaly*, Classifier are "end" nodes, so they take input and return something (not SDR) which is not computable by SP/TM anymore) 

> How does a user determine what a dimension should be?

Input: given by data. 
SP/TM: does not know (all code works Ok with 1D columnar structure), can try (MNIST feels naturally for 2D) 

> Could dimensions be programmatically generated? 

can you explain? You can do parameter optimization (including dimensions), but that (aka "swarming") is not supported by c++ code. 

>    What happens to dimensions in a Fan-In condition where an input has more than one output connected?

I think all "next level inputs" should inherit dimensions from their output node.

>    Can a dimensions be propagated from one output to the input of the next region or regions and what does it mean if the dimensions are different?

you are reading my mind :), yes. 

..different? You can encode any nD as 1D, but the decoding node needs to know what the original n was. Or keep using it as 1D.

**Comment by dkeeney** [comment]
> I think dimensions of a region (in/out) should match the dims of its algorithm

YES! This is what I was hoping was the case.  The networkAPI has a LOT of code dealing with dimensions but it was mostly to support the LinkPolicy and the way it arranged the splitter map....nothing to do with biology as far as I could determine.

> I think all "next level inputs" should inherit dimensions from their output node.

Ok, that was my feeling too.

> In fact, the only part able to change topology is SP (dims(input) -> dims(columns))

Ok, this is core to the point.  So it is only SP that should set the dimensions.  And where should it get the dimensions.  Should this be a configuration parameter?  Right now we only can set the 1D width with 'columnCount' parameter.  Perhaps this should be a comma separated list for nD.

Another alternative is to set a global dimension in the NetworkAPI parameters that specifies what dimensions all SP's should use.

Also, the encoders....would it be useful for them to have dimensions?  Its probably not biological.

**Comment by breznak** [comment]
> Ok, this is core to the point. So it is only SP that should set the dimensions. And where should it get the dimensions. Should this be a configuration parameter? Right now we only can set the 1D width with 'columnCount' parameter. Perhaps this should be a comma separated list for nD.

I don't know how SPRegion, but in SP this works correctly as constructor's vectors `inputDimension, columnDimensions`, so I think SPRegion should match that case? 

https://github.com/htm-community/nupic.cpp/blob/master/src/nupic/algorithms/SpatialPooler.hpp#L73

> Another alternative is to set a global dimension in the NetworkAPI parameters that specifies what dimensions all SP's should use.

nope, in the hierarchy, you want to have different SPs with different columnCounts and dimensions. 

> Also, the encoders....would it be useful for them to have dimensions? Its probably not biological.

encoders, are not very biological (there's no "organ" that translates a real number to a string of bits, retina is a biological encoder for images in a way). But yes, it's natural that encoders have dimensionality, a good example is a simple image encoder for black and white images, where encoding is a 2D matrix with ones on black spots.

**Comment by dkeeney** [comment]
> but in SP this works correctly as constructor's vectors `inputDimension, columnDimensions`, so I think SPRegion should match that case?

Absolutely ... but I am trying to figure out what to pass in for inputDimension and columnDimensions.  Right now, the inputDimensions are taken from the incoming SDR which gets its dimensions from the output of the connected region.  The columnDimensions are created either from the spec (if fixed size is specified) or by calling region->getNodeOutputElementCount() which tells me what the region impl thinks it should be (usually from parameters).  Either case it is 1D.

I will try to figure out a way for the Spec to tell me:
- if columnDimensions should be created with a fixed size from the Spec (1D)
- If columnDimensions should be created from its own parameters (nD).  Right now its 1D only.
- if columnDimensions should inherit dimensions from one of its inputs on the same region.  A way to pass dimensions downstream.  This would be new.

We could use the region->setDimensions( ) function but it does not specify which output. Global per region.  So I was thinking of removing this.  It was originally intended to set dimensions for the splitter map and is not really the same thing.

**Comment by breznak** [comment]
> The columnDimensions are created either from the spec (if fixed size is specified) or by calling region->getNodeOutputElementCount() which tells me what the region impl thinks it should be (usually from parameters).

If I understand it correctly, the Spec is used to setup a Region, its algorithm, and connect the region within the network (links). Then, Spec must expect all required arguments for the algorithm (here input/columnDimensions) and can honor other optional params. 

> If columnDimensions should be created from its own parameters (nD)

so I'd stay this would be the only option you should support. 

> A way to pass dimensions downstream. This would be new. 

why would you need to do that? 

> We could use the region->setDimensions( ) function but it does not specify which output. Global per region. 

This would be what we're saying, a region can output only dimensions that match the region, and its underlying algorithm.

**Comment by breznak** [comment]
> This would be what we're saying, 

...or scratch that, a region should not set neither of its diomensions: 
- input obtained from lower region, 
- output user-given from Spec (for both Region and its algo)

**Comment by dkeeney** [comment]
I am a bit confused.  

>    (for both Region and its algo)

There is only dimensions on the input and dimensions on output.  I know of no others.

>     input obtained from lower region,

I assume you mean input dimensions are determined by the output to which it is connected. (upstream).

>   output user-given from Spec (for both Region and its algo)

I assume you mean "from Input Spec if a fixed size is given and otherwise from passed in parameters".  

Right now, the only parameter I have that affects output dimensions is "columnCount".  That would be 1D.  So I need to add something to collect a full dimension from the passed in parameters.  These are passed as a quoted yaml or JSON string, parsed and presented to the region impl.  I will have to see if this can pass an array.

**Comment by breznak** [comment]
> There is only dimensions on the input and dimensions on output. I know of no others.

correct. Sorry for confusion, that note should just mean that region and algo would have the same dimensions. 

> I assume you mean input dimensions are determined by the output to which it is connected. (upstream).

R1 -> R2

R2's input dimensions == R1.outpuDims(); R2's columnDims (output dims) are set be Spec, params. 

> I assume you mean "from Input Spec if a fixed size is given and otherwise from passed in parameters".

what does "fixed sized" mean, and do we need it? 

>  otherwise from passed in parameters".

I want to say sth like 

```
SPRegion R2 = new SPRegion("columnDimensions 100x100", inputFrom=R1, ...) 
```

> . I will have to see if this can pass an array.

best option. Or pass a string, and you have VectorHelpers:: vectorFromString, or something, that'd do the job.

**Comment by dkeeney** [comment]
Ok, I think we are on the same page just using different terms.

> SPRegion R2 = new SPRegion("columnDimensions 100x100", inputFrom=R1, ...)

well, more like:
```
net.addRegion("R1", "TestNode", "");
net.addRegion("R2", "SPRegion", "{columnDimensions: '100x100'}");
net.link("R1", "R2");
```
The input dimensions are assume to come from R1
R2's parameters in the third field needs to be valid Yaml orJSON syntax.  I will have to figure out what that needs to be. The parameters could also be placed in a yaml file along with lots of other parameters and the contents of the file passed in the third argument. If an argument is not provided, its value is taken from the default value in the Spec for the field.

> what does "fixed sized" mean, and do we need it?

Well the spec has always had this feature that if the 'count' field for an input is specified in the spec with something other than 0, it overrides everything and sets the input buffer to that size (1D).  If the connected output has a different size, its an error.  If the output does not set a size, the output is set to the input fixed size.  I have no idea what it is used for...someone must have thought it was a good idea.

**Comment by breznak** [comment]
>  [fixed sized] I have no idea what it is used for...someone must have thought it was a good idea.

A lot has changed since then. SP and SDRs now support dimensions, not at all common in older code. I'd think this could have been just for convenience (you set one param and good to go), so if you look one more time and cannot find anything, I'd say go ahead and remove that as well.

**Comment by dkeeney** [comment]
One more question.  What about the Fan-In situation.  How should I set the input buffer's dimensions?

For example:  One input with two or more outputs that connect to this one input.  The outputs might not have the same dimensions.
```
     A -> D
     B -> D
     C -> D
```
Possible options are:
- flatten the output dimensions and append the buffers.  The D input would have a 1D dimension with a width which is the sum of the elements of all of the sources.
- Add another dimension.  If A, B, and C do have the same dimensions, D would have that dimension and add another dimension which is the number of inputs.  For example, if A, B, C are all 20X30 then the D input would have 3X20X30.

However, thinking about what the SP does.  It is simulating the incoming connections which connect it somewhat random order; a bundle of connections.  It effectively wipes out all effects structure in incoming data and creates its own based on relative location within the minicolumn.  For that reason I would think that just a flattened 1D dimension should be used for the FAN-IN condition.

What do you think?

**Comment by ctrl-z-9000-times** [comment]
My 2c: Topology is a large scale effect.  Most of the prior state of the art HTMs are small scale and as such use 1 dimension and ignore topology.  These experiments concatenate 1D  SDRs into bigger 1D SDRs.  Then the SPs treat all inputs and all minicolumns as equidistant (assume global inhibition).

Large scale experiments will need the ability to join SDRs together in a way that can preserve topology.  My current work with SDR concatenation supports this by allowing concatenation along any dimension.  As a requirement: all dims except the axis of concatenation must be the same.

**Comment by dkeeney** [comment]
>  all dims except the axis of concatenation must be the same.

I don't think I can guarantee any dimension on any link being concatenated.

But I guess I need to go back to HTM School and watch the SP section again.  It has been over a year since I watched it.  I still have trouble visualizing how topology (large or small) can have any impact on the results generated by SP.

**Comment by ctrl-z-9000-times** [comment]
> I don't think I can guarantee any dimension on any link being concatenated.

Thats fine if its all 1D or flattened to 1D, which is the common use case IMO.

I visualize topology by thinking about two extreme cases of it:
1) local neighborhoods, where all of the cells are very close together, so close that they are more like room mates than neighbors.
2) global areas, where cells are so far away from eachother that they are not neighbors but rather distant cities, with a telephone line between them.
3) somewhere between very local and very distant.  There is a messy grey area where neurons in the spatial pooler can effect each other in proportion to their proximity, at least according to numenta.  This grey area is incredibly time consuming to compute and offers no clear benefit to the neural computation.

**Comment by dkeeney** [comment]
Ok, I went back and reviewed the SP section of HTM School and that is what I had remembered.  The output is decoupled from the input.  But when I then went on to the Topology session in HTM School then it became apparent why you want to have dimensions in the input space and it does affect the SP's output if topology is employed.  So, I will continue to think on this, how to make this useful.

**Comment by dkeeney** [comment]
Ok, So I added dimensions back into NetworkAPI.
- Each Input can have a dimension.  
- Each Output can have a dimension.
- If an input's dimension is not set, it gets it from the other end of the link.
- If an output's dimension is not set it tries to get it from the other end of the link.
- When the link initializes, it checks both ends of a link.  If a dimension is still not set it asks the region implementation what the dimension should be.  The region presumably would get that from some parameter.  It could also use the region level dimension.
- There is a separate 'Region' dimension that a region impl can use to set the default output (or for any other purpose).  This is configured with "{dim: [2,3]}" syntax in the parameters or by calling setDimensions(dim).  This is somewhat like how the original LinkPollicy code used dimensions.  So this maintains API compatibility.

**Comment by dkeeney** [comment]
But I now have something else that came up. 
In the SpatialPooler.cpp line 418
```
NTA_CHECK(inputDimensions_.size() == columnDimensions_.size())
```
The inputDimensions is set by the dimensions on the incoming SDR which is defined by the output of the connected region, which in this case happens to be a ScalarSensor region which as only one dimension.

The columnDimensions is set by the dimensions on the output SDR which is defined by a setting in the SPRegion configuration, which I happen to set to a 2D dimension for this test.

This check in the SpatialPooler means that we cannot have a 1D as input and 2D as output for the SP.  Since it is the SpatialPooler that I would expect to be doing topo conversions like this it implies that all regions and their links must all be 1D or all 2D, or all 3D ... i.e. all the same throughout the network.  Maybe that makes since to someone but somehow it does not seem right.

**Comment by dkeeney** [comment]
I found a way around this...If I have a 1D array that must match with a 2D dimension I just add a dimension with a value of 1.  So, a 64 element array becomes a 1X64 2D array.  

Not to hard to do by adding region parameters but the user has to figure out the dimensions and where to add them.  It would be a pain to do this with logic unless I make everything with three dimensions.  {dim: [200,1,1]}  Is it simple to add the 1 dimensions in the SP or SDR as needed?

Adding the 1 dimensions does get around the check but does that mess up anything in SDR or in the SP?

**Comment by ctrl-z-9000-times** [comment]
> So, a 64 element array becomes a 1X64 2D array.

Nitpick: I think it should append the new dimension: 64 -> 64x1

>  Is it simple to add the 1 dimensions in the SP or SDR as needed?

The Spatial Pooler requires that its input & output have the same number of dimensions.  So as long as you're consistent about appending dimensions of size 1, it should work.

The SDR can add & remove dimensions by attaching an `SDR_Proxy` class.    Caveat: it's a read-only SDR.  You must write data to the original SDR with the original dimensions.  
```C++
SDR A({ 64 });
SDR_Proxy B(A, {64, 1});
A.setDense( data );
B.getDense() -> data;
```
OT: I'm considering renaming the `SDR_Proxy` to `SDR_Reshape`.  I think it's a more descriptive name.

**Comment by dkeeney** [comment]
SDR_Reshape is more descriptive imho.

But in this case, I am establishing the dimensions before I actually create the SDR's so I should be good.
So, the answers to my questions:
- I need to make sure the dimensions match before calling SP, actually before creating the Inputs and Outputs..
- Using 1 as a dimension is ok.

**Comment by breznak** [comment]
NetworkAPI and Algorithms now do support dimensionality, 
- Do we still need Dimension class? 

Otherwise, we can probably close this issue.

**Comment by dkeeney** [comment]
yes, I use it.  It is basically a wrapper around a simple std::vector<UInt32> with a few more additional functions.  It is compatible with SDR too.
