### ISSUE TITLE
SP strip unlearned columns implicitely

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#281]
SP has a method stripUnlearnedColumns(): 

> /**
Removes the set of columns who have never been active from the set
of active columns selected in the inhibition round. Such columns
cannot represent learned pattern and are therefore meaningless if
only inference is required.
@param activeArray  An array of 1's and 0's representing winning
columns calculated by the 'compute' method after disabling
any columns that are not learned.
*/
void stripUnlearnedColumns(UInt activeArray[]) const;
void stripUnlearnedColumns(SDR& active) const; 

currently the method is not used, the user can call it manually as follows: 
```
sp.compute(input, active);
sp.strip(active);
```

I suggest the following: 
- remove the method from public API
- make compute() call it automatically if learn=false parameter is passed
  - and/or integrate it into compute, such that `strip` is called before inhibition (a/ makes inh faster, b/ inh could work better when working on smaller/correct set of columns)

**Comment by breznak** [comment]
concerns: 
- is it biologically plausible? 
- what about anomaly. Will it work with columns removed this way?

**Comment by ctrl-z-9000-times** [comment]
Shouldn't boosting ensure that all columns activate?  If there are unused columns then either your code/parameters are broken or you do not have enough data.

**Comment by breznak** [comment]
> I vote to drop this method altogether. 

I'll make a test to see if the method ever removes some columns, if not, we should remove it to avoid confusion. 

> Shouldn't boosting ensure that all columns activate? 

you may not be doing boosting, or with not enough strength

> If there are unused columns then either your code/parameters are broken or you do not have enough data.

this is easy to say, but can probably occur. A counter example is (actually a problem we've observed with boosting) a large SP, and a simple problem (so columns become unused, and boost artificially boosts them, causing fake anomalies)
