### ISSUE TITLE
SDR_Concatenate: implement inverse as split()

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#300]
```
vector<SDR> SDR_Concatenate::split(const vector<UInt> splitSizes, const SDR& source) {
  NTA_ASSERT(sum(splitSizes) == source.size());
  //split
}
```

**Comment by ctrl-z-9000-times** [comment]
This would be used as part of the decode operation aka top down compute.

**Comment by ctrl-z-9000-times** [comment]
I'm closing this issue as won't fix.  See issue #297 for more discussion about why.

**Comment by breznak** [comment]
Do we have an issue for Split? I think we still need that to emulate MultiEncoder (concat, split)

**Comment by ctrl-z-9000-times** [comment]
The only use-case for splitting an SDR was to implement the `decode` method for a multi-encoder.  Since we are not going to implement the decode methods, this is not needed.

**Comment by breznak** [comment]
> not going to implement the decode methods, this is not needed.

I thought also Classifier will need split(), but it's better it trains on the packed data.

**Comment by ctrl-z-9000-times** [comment]
I'm not sure how the classifier would use split.  The classifier (as its written now) needs to deal with missing data points, which complicates everything and means that it needs a bunch of logic which is not general purpose.

**Comment by breznak** [comment]
> I'm not sure how the classifier would use split.

Let's have inputs in1, in2 -> encoders: enc1, enc2 -> concat: <enc1, enc2> -> SP, TM train on <enc1,2> ;
Than if Classifier should train on {enc1, in1}, {enc2, in2}; or
{<enc1, enc2>, {in1, in2}}

**Comment by ctrl-z-9000-times** [comment]
You mean to use the classifier to decode?

**Comment by ctrl-z-9000-times** [comment]
If the user concatenated two SDRs then they should have access to the original input SDRs, so they don't need to split it.
