### ISSUE TITLE
Spatial Pooler Parameter Structure

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#332]
The Spatial Pooler has too many parameters.  It would be much easier to work with the spatial pooler if it used a structure to hold its parameters.

For a good example of parameter structures in action, look at the files:
```
src/nupic/encoders/ScalarEncoder.hpp
src/nupic/encoders/ScalarEncoder.cpp
```

If someone wants to work on this I will be happy to help.

**Comment by ctrl-z-9000-times** [comment]
Related PR #279, #5, #209 
Would help with issues: #92, #316, #86

**Comment by breznak** [comment]
I would like to see this as a requirement in #295 (albeit the "Computable" is hard to describe generally enough)

**Comment by ctrl-z-9000-times** [comment]
I'd like to close this issue as WON'T FIX.
- Changing this would break all of the existing SPs.  It's not as simple to fix this without breaking compatibility.
- The current way of using the SP works.  New features can be added to the SP with setter/getter methods.
- There are easier ways to improve the usability of this library.  My guesstimate of added value per hour of work for this issue is too low.
- In the future, algorithms with many parameters should definitely use a parameter structure.
