### ISSUE TITLE
SDR Classifier Cleanup

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#335]
The SDR Classifier is more difficult to use than it needs to be.  I've done a thorough review of this class and here are my suggestions for your consideration.

## Ideas for Improvements:

Most of these ideas could be implemented without breaking the API compatibilty.

### Split into two classes:
* SDR_Classifier - This class would be stateless.
* SDR_Predictor - This class would contain a queue of SDR's and SDR_Classifiers. It would manage the time aspects of predicting several steps into the future, as well as dealing with missing data points.

### SDR_Classifier:
- [ ] Integrate with SDR class
- [ ] Add methods learn & infer
- [ ] Make recordNum optional
- [ ] Parameter Structure
	* Argument category belongs here, not in compute
	* Allocate for known size inputs & number of categories
	* Default to `steps=[0]`
- [ ] Nitpick: use spaces not tabs
- [x] Remove method `persistentSize`?
- [ ] Remove method `Operator==`?

### Python Bindings:
- [ ] Python unit tests are still in the python repo!
- [ ] Check default values are sane & the same as in C++
- [ ] Keep lines to a reasonable length (one line is 163 characters long!)
- [ ] Need pickle support, loadFromString is useless without a save method

### ClassifierResult class:
<strike>

- [ ] Fixme: private: `std::map<Int, PDF*> result_; //TODO do not use pointer T*, but T in this class`

- [ ] Documentation uses terms which are no longer in common use: "CLA"

- [ ] Remove `virutal` from methods.  This class is not meant to be subclassed or extended.

- [ ] Method `createVector` should be private

- [ ] `Operator==` uses hardcoded epsilon for floating point comparisions

- [ ] Remove `Operator==`?

</strike>

### Alternative plan for ClassifierResult:
- [x] Replace this class with a typedef of `std::map<UInt, PDF>`.  This class doesn't actually do anything, it just holds the result of the SDR-Classifier.  It doesn't add anything of value to the library.
    - [x]  getClass could be moved into the SDR-Classifier

**Comment by breznak** [comment]
Note, this PR should be decided (and implemented) before #309

**Comment by ctrl-z-9000-times** [comment]
I'd like to split this into two classes.
1) SDR_Classifier - This class would be stateless.
2) SDR_Predictor - This class would contain a queue of SDR's and SDR_Classifiers.  It would manage the time aspects of predicting several steps into the future, as well as dealing with missing data points.

The reason for doing this would be to make the SDR_Classifier easier to use, while keeping the features of the SDR_Predictor.

**Comment by dkeeney** [comment]
Sounds good to me.  Will you be needing a plugin region for each of them?

**Comment by ctrl-z-9000-times** [comment]
If you want to keep the API working exactly as it is now, then you would only need a region plugin for the `SDR_Predictor`.

**Comment by dkeeney** [comment]
Sounds good. 👍

**Comment by ctrl-z-9000-times** [comment]
I have begun working on this in branch `sdrc-reorg`

**Comment by ctrl-z-9000-times** [comment]
I'm going to remove the handling of actual values.  The current SDR-Classifier on master branch estimates two things:
1) The bucket index / category of the input.  This will stay.
2) The actual value of the input, which assumes it is a scalar input.  This works by doing a moving exponential average of the input values in each bucket.
    - The primary reason for removing the actual value from the classifier is that it's implementation does not in any way use the input SDR.  The purpose of the SDR Classifiers is to determine if the SDR contains some piece of information which the system was presumably trained on.
        * Because this feature does not relate to the input SDR, it will give users an unfounded sense of SDR quality.  If the user wants better resolution of the estimated values, then they need more buckets.
        * Furthermore, an exponential moving average is a very simplistic way to estimate the value of a scalar value.  There are better ways to do this kind of estimation, using derivatives and advanced statistics.  This library does not and will not do any of that. 
    - I'm pretty sure that the current implementation has a bug or two in it.
    - This will greatly simplify the API & Usage of SDR-Classifiers.

Thoughts?  Objections?

**Comment by breznak** [comment]
> Because this feature does not relate to the input SDR, it will give users an unfounded sense of SDR quality. If the user wants better resolution of the estimated values, then they need more buckets. 

I agree with this. But we'll need a doc + example, how the users need to adjust their classifier/encoder if needed.
