### ISSUE TITLE
StringUtils cleanup 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#378]
remove most of unused (& untested) `toXXX` methods from `utils/StringUtils`, 
see what elese there is unused and rm that

**Comment by ctrl-z-9000-times** [comment]
See also issue #175.

**Comment by ctrl-z-9000-times** [comment]
I used the following commands to find all references to the `namespace StringUtils`
```
grep -rn StringUtils bindings/
grep -rn StringUtils src/
```

StringUtils is used in the following places:

Uses only function `toUInt32`:
- src/nupic/regions/VectorFileSensor.cpp:40:#include <nupic/utils/StringUtils.hpp>
     - This could be rewritten to use the method `stringstream >> integer`.  Alternatively this method coud be moved to the file VectorFileSensory.cpp.

Uses only Trim function:
- src/nupic/os/Path.cpp
- bindings/py/cpp_src/bindings/sdr/py_SDR.cpp
- bindings/py/cpp_src/bindings/sdr/py_SDR_Metrics.cpp
     - This could easily be replaced by a regex.

Includes but does not use anything:
- src/nupic/engine/RegionImplFactory.cpp
- src/nupic/engine/Network.cpp

No tests include StringUtils...

**Comment by ctrl-z-9000-times** [comment]
The string utils files were removed in PR #496.
