### ISSUE TITLE
SDR consider randomize() takes RNG argument

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#381]
instead of seed, 
See https://github.com/htm-community/nupic.cpp/pull/375#discussion_r272838793

**Comment by ctrl-z-9000-times** [comment]
For C++ `SDR::randomize` does accept an instance of `Random`.
For Python I made `sdr.randomize` accept an `int` because it's easier to work with.  We should add a binding for `Random` too.

**Comment by breznak** [comment]
Fixed in #403
