### ISSUE TITLE
SDR getSparse() should be sorted.

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#382]
what are it's implications? 
- it would make some algorithms using SDR faster by knowing the list is already sorted 

from https://github.com/htm-community/nupic.cpp/pull/375#discussion_r272841427

**Comment by ctrl-z-9000-times** [comment]
Many fast algorithms rely on sorted data.  The SDR class should sort its sparse formatted data.  

The problem with having sorted data is that the user can't be trusted to sort their data, at best they'll forget to do it, at worst they'll use an insertion sort.  The users data needs to be cleaned.  Here is how I think we should deal with it:
 - C++ should only check in debug mode.  C++ programmers need to know to use debug mode.
 - Python should always check for sorted data.  If it detects unsorted data it should sort it.

**Comment by breznak** [comment]
- let's get this implemented before v1.0 before users start using SDR. 
- implementation
  - I think `SDR_sparse_t` could be a `std::set`; it has advantages of:
     - is sorted
     - also deals (away) with duplicates
  - if we wanted to keep using vector for `sparse_`, getSparse() should return vector(set(sparse_)); 

Result: 
 - we'll be able to rm lot of isSorted, rmDuplicates checks in SP, TM,.. 
OT: 
- should we have `const getSparse()` which would not break `sparseIsValid_`, and non-const getSparse() which would automatically invalidate it? (assuming user is changing the data he just requested access to)

**Comment by breznak** [comment]
> think a set is a bad idea.

what is a disadvantage of set? It’s native type with both of the features
we desire: sorted and unique.

A disadvantage being a single insert is slower log N vs O(1). But that may
very well be a premature optimization

-- 
Marek Otahal :o)

**Comment by ctrl-z-9000-times** [comment]
Inside of the STL, a set is almost certainly a balanced binary tree.  Trees allow for fast insertion, querying, removal of individual elements.  These are three things we don't need from the sparse data.
- Typically SDRs are overwritten every cycle, not modified by adding/removing elements.
- To query an individual bit of the SDR, use the dense format data because it has constant access time (thanks to RAM).

A typical use case of the sparse data is to iterate through it, for which vectors are better than sets.

**Comment by ctrl-z-9000-times** [comment]
Another consideration is that all of the legacy code expects a buffer, which `vector.data()` provides, but which the set does not.

**Comment by dkeeney** [comment]
That is probably the most compelling argument for vector.
If the legacy code could be changed to work with a set then maybe there would be some advantage.

**Comment by breznak** [comment]
> Another consideration is that all of the legacy code expects a buffer, which vector.data() provides, but which the set does not. 

I was inclining for set as a first choice too, but this is an important decision factor. 
Let's go with vector first, then we can try set later on. 
THe legacy code is slowly being removed #337

**Comment by breznak** [comment]
from #383 https://github.com/htm-community/nupic.cpp/issues/383#issuecomment-482138237 
If we used set for SDR_sparse_t, 

union, intersection, merge,... could be removed and provided by the STL.

**Comment by ctrl-z-9000-times** [comment]
>  could be removed and provided by the STL.

I'd still like to provide these methods.
- They provide error checking
- They have been checked for errors (via unit tests)
- They are easier to use than the STL
- They are well documented

> merge

I assume you mean concatenate?  Concatenate actually can not be done by the standard library, at least not in one or two lines.

**Comment by ctrl-z-9000-times** [comment]
Fixed in PR #495
