### ISSUE TITLE
SDR coordinate format

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#396]
SDR_coordinate_t uses format where coordinates are grouped by axis. 
Is this some commonly used format, or does it have important advantage? 

From user's perspective, I'd welcome coordinate format as a set of points, where each point is an N-let of coordinates. 
So
```
A = new A[10][10];
A[0][0] = 1;
A[0][2] = 1;
A[0][5] = 1;

```
would be encoded as `{ {0,0}, {0,2}, {0,5} }`, instead of `{ {0, 0, 0} ,{0, 2, 5} }`

We could change the format, provide both, or let it be.

**Comment by ctrl-z-9000-times** [comment]
The difference is the number of vectors which need to be allocated:
 - Group by axis has (number-of-dimensions + 1) many vectors
 - Group by point has (number-of-points + 1) many vectors

And also, group-by-axis is what numpy uses.

**Comment by ctrl-z-9000-times** [comment]
The coordinates are are grouped by axis for memory performance reasons.
For ease of use, the SDR provides the method `sdr.at( coordinates )` which works with coordinates in the normal format.

I'm going to go ahead and close this issue.  We can devise ways to make coordinates easier to use, if it becomes an issue.
