### ISSUE TITLE
Examples (hotgym, mnist?) do not run out of the box! 

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#414]
In followup to Matt's experimentation #389, 
The examples don't run out of the box, that is a bad first experience. 
- it's due to dynamic linking to lib nupiccore, 
So we should either
 - [ ] put a doc in Readme how to run the example
 - [ ] link examples with this library statically 

Duplicate of #272

**Comment by dkeeney** [comment]
>  link examples with this library statically

Linking statically would be the best in my opinion.  The reason for dynamic linking was to test the dynamic library generation.  Perhaps we should do that elsewhere.

**Comment by breznak** [comment]
Fixed in #434 , thank you!
