### ISSUE TITLE
Improve SP, TM bindings and py tests

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#415]
Followup to Matt's experimentation with this repo, #389, 
we ran into some issues when using SP, TM, SDR with the python bindings. 

https://gist.github.com/breznak/906f75ca19cd0b3bd38a2a3f0eee3ad0#file-pyspexperimenthtm 

- [ ] add python bindings tests for improting and basic usage of SP, TM, SDR
 - [ ] a small "testExampleUse()"

**Comment by ctrl-z-9000-times** [comment]
I can add an overload to the compute method for using SDR's with the SP.  It should resolve these problems.

**Comment by breznak** [comment]
> I can add an overload to the compute method for using SDR's with the SP. It should resolve these problems.

To pybindings? It would be great. 
#348 aims to switch to SDR only compute, it should have some/all of that implemented. 

Generally, we need a more high-level py test that uses SP, TM. 
 - [ ] we used SDRs, TM worked, SP had the problem you mention, probably. 
 - [ ] numpy arrays semi-worked (ok for some scenario, but segfaulted for other), therefor we went with SDRs eventually.

**Comment by ctrl-z-9000-times** [comment]
> Generally, we need a more high-level py test that uses SP, TM.

I'd like to close this issue as resolved, via the new hotgym example, see PR #480.
