### ISSUE TITLE
Random must not ignore seed in multiple instances

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#417]
Random should not use static members, esp `static_gen` and `static_is_seeded`, otherwise the first instance of random sets the seed, but seed is ignored for any other random instance during the runtime! 

From Random.cpp
```
bool static_gen_seeded = false;  //TODO avoid the static variables?
std::mt19937 static_gen;
```

Example of the problem:
```
sp = SpatialPooler(..., seed = 42); //OK, has rng with seed 42
rng = Random(1); //has rng with seed 42, not 1!
```
and 
```
rng = Random(1); //OK, seed = 1
sp = SpatialPooler(..., seed = 42); //has rng with seed 1!
```

**Comment by ctrl-z-9000-times** [comment]
Random only uses the static generator if `seed == 0`.  If `seed > 0` then it uses the given seed.

This is from the unit tests for Random.  I think it would reproduce this bug, if it existed:
```
  Random r1(1);
  Random r2(2);
  ASSERT_NE(r1.getUInt32(), r2.getUInt32());
```

**Comment by breznak** [comment]
> This is from the unit tests for Random. I think it would reproduce this bug, if it existed: 

yes, I was also looking into this and my description is imprecise. 

Still, in WIP PR #397 I had different results for these scenarios (compared with deterministic/"gold" check for SP/TM): 
```
Random r(1);
SP sp();

vs. 

SP sp;
Random r;
```

I'll verify if this is the case, or some other mistake on my side.

**Comment by breznak** [comment]
Closing as won't fix, this was my mistake. 
Sorry for confusion. 

The above scenario passes OK in both cases. The "bug" was that I had mismatch between hand-written values for SP, encoder outputs using different rng seed.
