### ISSUE TITLE
Windows build: link performance hint: use /LTCG

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#441]
During the Windows CI build, we get a number of 

> UnitTestMain.obj : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance

We should try adding that to the build config.

**Comment by dkeeney** [comment]
yes, I agree with that.
If I remember correctly that change will cause a warning in the debug build because it does not like /LTCG but for the CI build this is a release build so we should have it on.

**Comment by breznak** [comment]
Fixed in #453
