### ISSUE TITLE
Provide missing AnomalyLikelihood from python

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#455]
as our cpp Likelihood is likely broken and untested, #124 

- Python Likelihood would go to `py/` where pure python code resides. 
- it should be easy to port as has very few requirements
```

import collections
import math
import numbers
import numpy
from nupic.serializable import Serializable
from nupic.utils import MovingAverage
try:
import capnp
except ImportError:
capnp = None
if capnp:
from nupic.algorithms.anomaly_likelihood_capnp import AnomalyLikelihoodProto
class AnomalyLikelihood(Serializable):
```
   - [ ] we need either: py bindings for MovingAverage (and port py tests) 
   - [ ] replace MovingAverage in py likelihood with python code for it. (maybe prefered?) 

This will be used for running NAB #205

**Comment by ctrl-z-9000-times** [comment]
I have a different (competing) design for this.  The TM class should keep an exponential moving average (EMA) of the anomaly, as well as an EMA of the variance (aka standard deviation squared) of the anomaly.

This would introduce a new parameter to the TM for the window size / time-scale of the EMA.

**Comment by breznak** [comment]
> I have a different (competing) design for this. The TM class should keep an exponential moving average (EMA) of the anomaly, as well as an EMA of the variance (aka standard deviation squared) of the anomaly. 

I won't be against if it's just a few lines of code, but I'm not a huge fan of cramming more (unrelated) code to TM. TM's job is to make predictions for T+1. Even that we added `TM.anomaly` was compromising its logical integrity for convenience. 

- the advantage of your (2 EMAs) solution would be much simpler implementation :+1: 
- disadvantage: peer-review: We'll probably still need AnomalyLikelihood for comparisons with Numenta's benchmarks.
  - if Likelihood in c++ never gets fixed & tested, we could probably live with original python-pnly #455 and your new for c++. 
 
- I'd prefer suggested solution with a virtual `float TM::getAnomalyScore()` which you could override with the new implementation without needing to add new code to TM.  

(but these comments are probably for a PR/issue with your suggested design)
