### ISSUE TITLE
Simplify SDR Reshape

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#482]
I'd like to replace the class `nupic::sdr::Reshape` with a method for the SDR class which directly modifies the SDR.  This would be much simpler, less error prone, and would make the python bindings work better.  The method would not change the data in the SDR so it would work on constant SDRs.

Replace all checks for `sdr.dimensions` with `sdr.reshape`.  The reshape method will check that the size is correct, which should still catch errors where the wrong SDR is given.

**Comment by breznak** [comment]
High-level I support this. 

> The method would not change the data in the SDR so it would work on constant SDRs. 

how would you suggest doing this? 

> Replace all checks for sdr.dimensions with sdr.reshape. The reshape method will check that the size is correct, which should still catch errors where the wrong SDR is given. 

ok, I would not say "replace all", 
- would sdr.dimensions still exit? (I find that quite useful, so each SDR has its own "parent shape", or would SDR become shapeless?

**Comment by ctrl-z-9000-times** [comment]
> how would you suggest doing this?

First mark sdr dimensions_ (the private access attribute) as mutable, which makes it possible to change it.

Then every class which cares about its sdr's dimensions must keep a private copy of the dimensions.  Dimensions still exists and is correct after the algorithms have set it, user can reshape it as needed.

**Comment by breznak** [comment]
I believe this is merged in, reopen if needed. thanks
