### ISSUE TITLE
License and Contributor agreement (CLA)?

### ISSUE THREAD

**Issue by dan-stromberg** [htm-community/nupic.cpp#492]
As people have been working on htm-community/nupic.cpp, are they using Numenta's Contributor  Agreement (https://numenta.org/licenses/contrib/)?

I understand that Numenta holds the copyright on most of the code, and that the code remains AGPL, but what is the copyright of the respective recently-contributed portions?

I heard that individual contributions to OSS projects are under each contributor's copyright by default, and that a Contributor License Agreement (CLA) is needed to keep the copyright simple.  Or in the case of Numenta, a "CA".

Is Numenta still requiring their CA be used?

I just examined "git log" on htm-community/nupic.cpp, and found 73 different contributors.

**Comment by ctrl-z-9000-times** [comment]
We are not numenta and we do not require any signatures from you.  All we require is that your contribution have a license which is compatible with the AGPL.

Indeed you do own the copyright for all things which you write!.  I recommend stating this fact at the top of any files which you write or modify, along with the date that you wrote it.  For example I write at the top of my files:
`Copyright 2019 David McDougall`
A file can have many contributors, each gets a copywriter notice.

All files in this project should have both a copyright and license notice, clearly displayed at the top of the file.  If you are unclear about the exact wording of either of these things you can copy & edit from an existing file.

**Comment by breznak** [comment]
Cobsidering this answered, please reopen if some questions remain
