### ISSUE TITLE
TemporalMemory without setConnectedPermanence()

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/nupic.cpp#494]
Hi Developer,
I am wondering why TM do not have the function member
setConnectedPermanence()
like in original TM.
Do you want to delete it for some reasons?
Thanks

**Comment by ctrl-z-9000-times** [comment]
Hi Thanh-Binh,

That method was intentionally removed as part of an optimization.  The connected permanence must now be given when the TM / Connections is constructor or initialized.

HTH

**Comment by Thanh-Binh** [comment]
Ok thanks
