### ISSUE TITLE
ArrayBase pull request.

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#51]
@breznak  I need your help.  I am trying to submit a pull request but having a bit of a problem.  Here is what I did:
1) Cloned the htm-community/nupic.cpp repository.  
2) Opened a new local branch "Array"
3) copied my source files for ArrayBase, Array, ArrayRef to the new branch.
4) Made a few changes so that it would work.  built and ran the unit tests.
5) committed the changes and pushed them to github.com/dkeeney/nupic.cpp Array branch
6) On htm-community/nupic.cpp repository, clicked the pull request button.  Tried to specify the pull request coming from github.com/dkeeney/nupic.cpp Array branch to htm-community/nupic.cpp Master branch.    But it will not let me select that combination.

Am I doing this all wrong?

**Comment by breznak** [comment]
@dkeeney wow, that would be a tremendous help, basing it directly off this repo! 
It might be a github problem, but I see your repo https://github.com/dkeeney/nupic.cpp/tree/Array 
does not have the "forked from ..." under its name.  
I'll be able to merge it, but I'll have to do tomorrow, I've been writing a paper all day.. 
Or you could try: 
- rename your nupic.cpp repo (in Settings, just to avoid name conflict)
- click "fork" here, on top right
- clone this repo under your account community/n.cpp -> dkeeny/n.cpp
- clone your dkeeny/nupic.cpp to local PC
(optionally fetch the branch with commits) 
- PR will now work

**Comment by dkeeney** [comment]
It will not let me clone again because the nupic.core repository is a clone of chhenning's clone which is a clone of htm-community/nupic.cpp.  This is the one that has my base branch which picks up the work by chhenning and my changes.
So, I will try to create a new Array branch off of the master of that repository and see if the pull request will be accepted at htm-community:nupic.cpp.

**Comment by breznak** [comment]
..or, you have write access here. Clone this repo locally, make branch, changes, push here (to a feature branch, please), and it will let you make PR from within this repo: feature->master.
