### ISSUE TITLE
Merge Region classes from dkeeney

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#54]
- [ ] SPRegion
- [ ] TMRegion
- [ ] tests

**Comment by dkeeney** [comment]
I think we did ok on this one.  Lets close it.

**Comment by breznak** [comment]
Reopening and actually marking as a high priority. 
We do not have the mentioned classes in this repo, although I know you've implemented them a long time ago. 

This is needed for more complex NAPI support in c++, something mentioned recently and useful for many examples. 

Please take a look when you are finished with your current stuff.

**Comment by dkeeney** [comment]
Ok, I will go find the C++ code for RegionTM and RegionSP and start a PR for each of them.
- RegionSP was fairly complete.  
- RegionTM was setup to call BacktrackingTMCpp and is missing the "Shim" that maps the arguments to TemporalMemory.  So there might be a little more porting from python to complete that class.

**Comment by breznak** [comment]
> Ok, I will go find the C++ code for RegionTM and RegionSP and start a PR for each of them. 

That'd be great :+1: 

Will we want bindings as a part of the PR, or separate? Or actually the Py Regions exist, so there will be no use for bindings?

**Comment by dkeeney** [comment]
finished in multiple PRs
