### ISSUE TITLE
Replace custom Random with std::uniform_random_distribution , remove "singleton"

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#60]
This will solve many problems and avoid non-related yet complicated code. 

- [x] replace shuffle and sample() methods with standard c++
- [x] replace custom Random with a std implementation
  - [x] verify it gives same sequence (for same seed) on all platforms
- [x] remove RandomImpl is a singleton "feature"
- [ ] move code cleanups

**Comment by chhenning** [comment]
I think the reason is that std::uniform_real_distribution is c++11 and that wasn't used when Numenta wrote the code. I could be wrong.

**Comment by breznak** [comment]
> I think the reason is that std::uniform_real_distribution is c++11 and that wasn't used when Numenta wrote the code. I could be wrong. 

I think this was historically a reason. Last time we spoke with numenta's engineers about this, they'd argue custom Random is good as you get deterministic (per given seed) results on all platforms. Truth is, you now get the same with `std::` :+1: 

>  it does not invalidate any algorithom's assumptions? 

I'm quite confident about this. It's more for "corporate" uses, where they could debug, etc (IMHO you can achieve the same now, see above). Wouldn't break anything, nupic is not a crypto library, the random more or less just helps. (Also, I recently discovered a bug that the Rand.getUInt() returned just half of its max range..so there you go with "custom" crypto ..)

**Comment by chhenning** [comment]
I would always prefer standard c++ to any custom implementation. Filesystem is another example.

**Comment by breznak** [comment]
I'll try this soon. 
A plan after a quick view: 
- replace shuffle & sample with std versions
- use std rng instead of RandomImpl 
- figure why singleton was needed? 

@lscheinkman someone from Numenta could shed some light on the current/historical need for custom Random, please?

**Comment by ctrl-z-9000-times** [comment]
If you seed the custom random number generator with -1 then it always returns zero.  What are the odds?
```
Random rng(-1);
while( rng() == 0 ) {}
// This loops forever ...
```

**Comment by breznak** [comment]
> If you seed the custom random number generator with -1 then it always returns zero. What are the odds?

 Thanks, that shouldn't happen, I'll have a look!

**Comment by breznak** [comment]
^^ is this with the current, or the PR in progress?

**Comment by ctrl-z-9000-times** [comment]
The current implementation, not std::random
