### ISSUE TITLE
Port integration tests to unit-tests

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#65]
from `src/test/integration/`  

- [ ] PyRegion
- [ ] CppRegion
- [ ] ConnectionPerformance-Test
- [ ] move other `src/examples/` to unit tests

this will
- simplify cmake
- better coverage
- easier to run tests in CI

**Comment by dkeeney** [comment]
I was going to suggest also moving the Py tests in nupic.cpp/bindings/py so
all tests were together.  However, these will be moved to a separate
repository along with the Python interface.  So lets leave them where they
are for now.
