### ISSUE TITLE
Remove SHOULDFAIL macros in tests, replace with EXPECT_THROW

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#67]
from gtest

**Comment by ctrl-z-9000-times** [comment]
This macro is only used in the file: 
`bindings/py/cpp_src/plugin/unittest/PyRegionTest.cpp`

This test is not being compiled or run.  See file `bindings/py/cpp_src/CMakeLists.txt` line 185, says `TODO: Finish these tests` and then it's all commented out.

**Comment by breznak** [comment]
No more mention of SHOULDFAIL, probably removed with some old-code cleanups. 
Closing as fixed.
