### ISSUE TITLE
Build Windows CI with native MSVC c++ compiler

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#69]
as now we build with some mingw, MSVC is capable, available as OSS now, let's see if we can get it in Appveyor CI. 
Would be better to build with native compiler. 

EDIT: 
MSVC on Win put off only after SWIG removal: 
see 
https://github.com/htm-community/nupic.cpp/issues/55#issuecomment-422553423
> I suggest that we hold off on Visual Studio until after you get rid of Swig. The numenta documentation says that it will not work unless you install a very old compiler. I was not able to get the bindings to build under Visual Studio with C++11 although I have not tried since we removed capnproto. And I agree MingW is not really a viable build environment.

**Comment by breznak** [comment]
Given current broken Win CI, and planned c++17 move, this is a prerequisite. @dkeeney @chhenning  if you have a windows machine, would any of you like to take on this task? Or submit your local "guide" to building on MSVC, I could try to do it though testing in Appveyor CI.

**Comment by dkeeney** [comment]
yes, I have a CMakeFile for building the C++ parts under Visual Studio.  I
am sure it would need to be modified to work with the repository but it can
work as a start.  You can find it in my repository
https://github.com/dkeeney/nupic.core/tree/base
This uses either hunter or VCpkg as a package manager but without boost or
the other dependencies we will probably not need a package manager at all.

**Comment by breznak** [comment]
Windows platform support temporarily discontinued (https://github.com/htm-community/nupic.cpp/issues/81) we'll reenable once again after successful transition to modern Windows environment: MSVC, -SWIG, ... the MingGW workaround was too problematic.

**Comment by breznak** [comment]
Reopening, still WIP
