### ISSUE TITLE
Remove Dimensions from the Link object.

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#72]
As a placeholder for things to do.
Dimensions are known to be obsolete and unused. By removing dimensions we can simplify the Link (also removing LinkPolicy) and provide zero copy for some links and automatic type conversion for those that need it.

As part of this I suggest replacing the "isSparse" in the Input and Output objects with a new NTA_BasicType so that data can be converted between dense and sparse automatically as dictated by the specs of the source and destination plugins.

Similar: #139

**Comment by breznak** [comment]
> Dimensions are known to be obsolete and unused. 

This is the dimensions and topology as for 1D/2D input and SP/TM format? What was the notification that it does not make sense? 

> replacing the "isSparse" in the Input and Output objects with a new NTA_BasicType so that data can be converted between dense and sparse automatically 

can you explain please?

**Comment by dkeeney** [comment]
>
> This is the dimensions and topology as for 1D/2D input and SP/TM format?
> What was the notification that it does not make sense?

I noticed that in the region implementations for SP and TM the spec showed
ns->singleNodeOnly = true;   This basically means ignore dimensions and
treat everything as a flat array.  So I went up on the general forum and
asked if dimensions were obsolete or was anyone using them...other than for
the unit tests or example Test_Node.  The response I received was
dimensions are not needed and could be removed.

By removing dimensions it simplified the Links and removed LinkPolicy.  It
is still possible to do multiple links out from an output and multiple
links in to an input.  A flat array can be thought of as any
multi-dimensional structure but is is conceptual only.

**Comment by breznak** [comment]
> Then SP converts from Real32 to Byte arrays. TM also does a conversion but I think it is to UInt. We can probably avoid some conversions and array copies if we are careful about types. 

The conversions within the pipeline are a poor design solution and can severely limit some performance optimizations, I want to force one type (can be changed at compile time) to all data-transfers within HTM. See #58 

> If isSparse feature were just another data type the automatic data type conversions in Array could handle it (if extended a little). 

I understand instead of `if isSparse` you want to have some SparseVector_t, and DenseVector_t ? 
This is :+1: 

> The response I received was dimensions are not needed and could be removed. 

Please be careful here, that answer cannot be true. It might not be used, but there IS difference!, in connectivity, local inhibition, etc. Imagine ordering 8 cubes in 3D vs 1D - 3D=fully connected, 1D~only to 2 neighbors. Given recent Numenta's interest in Thalamus, I consider this code still useful (possibly unexplored in current official implementation). Ofc, if it really is a big pain, we could remove it from Regions..

**Comment by dkeeney** [comment]
-- about data types in the links.
The data type is currently set in the the spec for each plugin (the Regon
Impl).  For example TestNote specifies both inputs and outputs to be
NTA_BasicType_Real64.  VectorFileEffector specifies NTA_BasicType_Real32
for input.  VectorFileSensor specifies two outputs "categoryOut" and
"reset" to be NTA_BasicType_Real32.

Over in Python, SP is expecting "bottomUpIn" and "topDownIn" to be
NTA_BasicType_Real32 but then internally converts them to Byte but treats
them like boolean.
TM specifies NTA_BasicType_Real32 for all 6 outputs and a 2 inputs but
internally it converts them to UInt32 but treats them as Boolean arrays.
Note that the "anomalyscore" output is actually NTA_BasicType_Real32 data
but might benefit if it were NTA_BasicType_Real64.

I would think that a good design would be for each algorithm should use
whatever type is optimum for it and allow the Link to convert as needed to
match the source outputs with destination inputs.  Requiring everyone to
use Real32 when they only need a bit is less than optimum.  As it is output
must convert from their internal format to Real32 and the input side must
convert from Real32 to their internal format; two conversions.  A better
way would be for the link to convert once but only if needed. And if not
needed, do a zero copy pass of the buffer.

I understand that both SP and TM just look to see if a value is 0 rather
than performing floating point math but still they are sending 4 bytes when
1 would do.

**Comment by dkeeney** [comment]
---about isSparse.
My thinking is that this should be another data type...something like
NTA_BasicType_Sparse. Those regions that send it or expect it can specify
that type in their specs.  The Array object could then hold this
information rather than rely on some external flag to know the format of
the data.  If conversions were handled by the Link then it can also convert
between this sparse format to anything else depending on what is specified
in the spec of the other end of the link.

**Comment by dkeeney** [comment]
--- about dimensions
The number of dimensions of data is still conceptual.  Any algorithm can
look at a flat array and treat it as any combination of dimensions. My
feeling is that the framework should not be involved with that
conceptualization. It should just pass a block of data and treat it as a
flat array.

doing so would remove a lot of complexity when most of the time it is not
needed.

**Comment by dkeeney** [comment]
But --- keep in mind that I am a new comer to this world of nupic.  You
have a lot more experience with it and know more about how it is used.
Particularly the use of dimensions.

What I have observed has been that the system overall is too complicated
and from the forums they seem to struggle with the infrastructure rather
than concentrating on the algorithms.  My impression is that many people on
the forums seem to be doing their own things and don't use this
infrastructure at all.

If I were designing this from scratch I would recommend something much
lighter weight (if possible). Possibly something where state could be
memory mapped to a file. But then, I don't know enough about how the brain
would do it.

**Comment by ctrl-z-9000-times** [comment]
This issue came up again and we decided not to remove the Dimensions class since we found valid uses for it.  See issue #273.
