### ISSUE TITLE
Replace APR libraries with std:: libraries (abandoned)

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#74]
Another placeholder for things to do.
Delete the APR library dependency and see what breaks.  Fix it by replacing it with calls to std:: libraries.
In the OS folder the Directories and Path objects can be implemented with #include filesystem .  This of course requires switching to C++17.

Edit: part of #47

**Comment by breznak** [comment]
After the capnp, I'd like to set for another advanture and bring c++17 (update CI, MSVC for Win,..) and then we can drop lots of dependencies

**Comment by dkeeney** [comment]
Ok, I will start in on this.  
But first I want to start over with a fresh clone of htm-community/nupic.cpp

**Comment by breznak** [comment]
> But first I want to start over with a fresh clone of htm-community/nupic.cpp 

Or you can clone numenta/nupic.core (1st level clone) so you can make PRs to both easily

**Comment by dkeeney** [comment]
That sounds dangerous to me.  I don't want to accidentally change anything
in numenta/nupic.core.  And since I don't understand GIT very well I should
keep it simple.

**Comment by dkeeney** [comment]
Ok, cloned htm-community/nupic.cpp
New branch for this project is "replace_APR"

**Comment by breznak** [comment]
> I don't want to accidentally change anything in numenta/nupic.core. 

don't worry, wouldn't happen. One thing is to clone something, other are push privileges. 
Clone of nupic.cpp is ok as well (y) 

I haven't found the branch, nor clone of project, in your profile yet. So when you're ready, please open a PR.

**Comment by dkeeney** [comment]
This PR is abandoned.  I was taking this in too large of chunks.  And in the process of trying to get MinGW to work, ended up with massive white-space changes that were mostly Just line-ending changes but it made compares almost impossible.  

So, See Roadmap Issue #81 for how I propose we proceed.

**Comment by breznak** [comment]
Closing, reopen if needed
