### ISSUE TITLE
Moving Python interface to a separate repository

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#75]
This is going to be a big PR.  During the move we can switch from SWIG to Bind11 as the Python interface.  This would mean we could support both Python 2.7 and Python 3.6+.

Start by ripping out the SWIG build.  @chhenning  already has a working interface for Bind11 that we can drop in. We just need to package it as a separate repository and set up a process for building in parallel with nupic.cpp.

Only the RegionImplFactory currently has calls into the Python world that would need to be resolved.  The way to do this is to have a subclass of RegisteredRegionImpl for each language interface that is passed to the factory to create a custom plugin.  RegisteredRegionImplCpp for plugins written in C++ and RegisteredRegionImplPy for plugins written in Python.  The logic for allocating and calling a python object via (PyRegion.cpp) would reside in this subclass rather than in the factory.  RegisteredRegionImplPy and PyRegion.cpp/hpp would reside in the Python repository.  All of the Python helper classes and the Python tests would also be in the Python repository.

When we implement the CSharp interface it can do the same thing...have its own subclass of RegisteredRegionImpl for allocating custom plugins.  The nupic.cpp code does not need to have any knowledge of Python or CSharp.

**Comment by breznak** [comment]
:+1:  with some expectation of discussion how to handle the modularity. I remember people say git submodules suck, but I find it as optimal way to integrate upstream and other necessary sugar here. From my experience, happened even with nupic-nupic.core, the separate repos lead to often API mismatches, repos go out of sync, pain handling code that touches both parts,... 
Given this, what I'm proposing: 
- strict build independence of features/bindings/languages
- but keep integrated all the ecosystem in one repo - here (src/nupic/{current c++ core}, src/bindings/{lang} feature-only code, ie C#, Py, CUDA bindings...) 

That way, this repo can be The go-to library for any NuPIC development usecase.

**Comment by breznak** [comment]
> A sub-directory CMakeList for each language perhaps would be sufficient. Each could have different dependencies but all depend on the C++ library. 

This is probably best! (maybe we can omit the git-submodule, and just copy the upstream - mostly still us)

**Comment by breznak** [comment]
@dkeeney with your work on pybind mostly finished! :100:  can we consider this closed? Python module is in a separate, optional directory with own cmake in `bindings/py/`. 
We can discuss removal to a separate repo once we have more users and this need pops out (?).

**Comment by dkeeney** [comment]
we can close this.
