### ISSUE TITLE
Problems with ConnectionsPerformanceTest

### ISSUE THREAD

**Issue by dkeeney** [htm-community/nupic.cpp#87]
When running unit_test I got this:
[ RUN      ] ConnectionsPerformanceTest.testTMLarge
0.013655 in temporal memory (large): initialize
24.1005 in temporal memory (large): initialize + learn
28.7102 in temporal memory (large): initialize + learn + test
/home/dave/cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:277: Failure
Expected: (tim) <= (28.0f), actual: 28.7102 vs 28
[  FAILED  ] ConnectionsPerformanceTest.testTMLarge (28723 ms)

This was compiled in debug mode on Ubuntu.
Two problems:
1) that actual time it takes to run (28 seconds)
2) The actual error which may be in the test facility.

**Comment by dkeeney** [comment]
A related problem is the time it takes for this test:
[ RUN      ] HelloSPTPTest.performance
starting test. DIM_INPUT=10000, DIM=2048, CELLS=10
EPOCHS = 10000
starting:  10000 iterations.Epoch = 9999
SP= 137,562,639,926,1133,1295,1335,1340,1346,1595
TP= 137,562,639,926,1133,1295,1335,1340,1346,1595
Total elapsed time = 20 seconds
[       OK ] HelloSPTPTest.performance (20699 ms)
[----------] 1 test from HelloSPTPTest (20699 ms total)

**Comment by dkeeney** [comment]
Here are some more examples:
in Debug mode, running on my Ubuntu machine here.  Very long times.
What we need is some way to shorten the time to run the tests and compensate for the speed of the target machine.  Perhaps run some evaluation of processor speed to compare against.  And adjust the amount of resources needed such that the test runs in a reasonable amount of time regardless of the machine on which it is ran.   Or....just not run this as part of unit_test.

[----------] 4 tests from ConnectionsPerformanceTest
[ RUN      ] ConnectionsPerformanceTest.testTM
0.004817 in temporal memory: initialize
21.867 in temporal memory: initialize + learn
26.3301 in temporal memory: initialize + learn + test
/home/dave/cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:269: Failure
Expected: (tim) <= (3.5f), actual: 26.3301 vs 3.5
[  FAILED  ] ConnectionsPerformanceTest.testTM (26362 ms)
[ RUN      ] ConnectionsPerformanceTest.testTMLarge
0.039923 in temporal memory (large): initialize
178.824 in temporal memory (large): initialize + learn
213.026 in temporal memory (large): initialize + learn + test
/home/dave/cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:277: Failure
Expected: (tim) <= (28.0f), actual: 213.026 vs 28
[  FAILED  ] ConnectionsPerformanceTest.testTMLarge (213184 ms)
[ RUN      ] ConnectionsPerformanceTest.testSP
1.22859 in spatial pooler: initialize
746.841 in spatial pooler: initialize + learn
750.429 in spatial pooler: initialize + learn + test
/home/dave/cpp/src/test/unit/algorithms/ConnectionsPerformanceTest.cpp:285: Failure
Expected: (tim) <= (10.0f), actual: 750.429 vs 10
[  FAILED  ] ConnectionsPerformanceTest.testSP (750514 ms)
[ RUN      ] ConnectionsPerformanceTest.testTP
11.4991 in temporal pooler: initialize

**Comment by dkeeney** [comment]
This is my machine in Debug mode.  In Release mode the
WatcherTest.SampleNetwork test core dumps.  So I am trying to figure out if
some compiler setting got messed up with the changes I am making...a
different problem.

The ConnectionsPerformanceTest is a good thing to have to make sure that
some change we make does not make a big difference in performance.  But we
need to scale it back so it takes only a few seconds to determine how fast
it is running on the slowest machine. Maybe only 10 iterations or
something.  Then compensate for the speed of the machine.  Perhaps some
sort of simple benchmark to measure speed of machine (maybe 1 second on
slow machine) then measure the speed of the algorithm in units of the
benchmark speed. We are not looking for high resolution in performance
time. More like orders of magnitude, so a short sample may be adequate.
Also, truncate the test when the time exceeds the Pass-fail threshold.
Don't try to finish it if it is going to fail anyway.

If running in Debug mode, skip the test entirely because debug mode is
always going to be slower.

**Comment by breznak** [comment]
> Perhaps some sort of simple benchmark to measure speed of machine (maybe 1 second on slow machine) then measure the speed of the algorithm in units of the benchmark speed. 

This is a really nice idea! 

> If running in Debug mode, skip the test entirely because debug mode is always going to be slower. 

I think our CI is running in Debug for reasons to make more checks, so this should run even in debug (the parametric slowdown above should handle it)

**Comment by dkeeney** [comment]
There seems to be a similar problem with the Serialization.testSP test.
takes 40 seconds to run on my machine (Debug mode).
