### ISSUE TITLE
Enhancement: TM accept external predictive input

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/nupic.cpp#88]
The temporal memory should accept predictive inputs (onto distal basal dendrites) from an external source.

There is a python example of this at: https://github.com/numenta/htmresearch/blob/master/htmresearch/algorithms/apical_tiebreak_temporal_memory.py

**Comment by breznak** [comment]
@ctrl-z-9000-times do you want to work on this feature, can I assign it to you?

It would be best if the implementation could be just an optional addition to the current TM impl, which I believe should be possible?

**Comment by ctrl-z-9000-times** [comment]
That sounds good @breznak, though I probably won't start work on this until I've wrapped up SP-topology enhancements (https://github.com/htm-community/nupic.cpp/issues/86), so it may be a while until I get around to this...

**Comment by ctrl-z-9000-times** [comment]
I would use this feature in the following ways:
* vertical connections between cortical layers.  Cortical layers 2/3 project to layer 4's distal dendrites.
* Horizontal connections between distant areas of the cortex.
* Efferent motor commands use this.

**Comment by breznak** [comment]
:heart_eyes: I'm very much into this. 

> vertical connections between cortical layers. Cortical layers 2/3 project to layer 4's distal dendrites 

I'd like to re-introduce the "topDownCompute" feature, which is a feed-back connection to HTM. It would allow us to get rid of *Classifier (which is imho an artificial concept), and offer more informed & natural way of re-constructing things (SDRs, inputs) ...I'll create an Issue for this. 

> Horizontal connections between distant areas of the cortex. 

Interesting, so something like hubs & connectomes? Would #156 use this implementation?

**Comment by ctrl-z-9000-times** [comment]
This feature allows the TM to be used as a tool for experimenting with minicolumns. 

I dont envision #156 using this, since i have some rather different ideas about Apical dendrites.

**Comment by ctrl-z-9000-times** [comment]
Implemented in PR #180
