### ISSUE TITLE
Separate tests as "external" project

### ISSUE THREAD

**Issue by breznak** [htm-community/nupic.cpp#91]
- [x] having a separate folder, namespace
- [x] separate CMake file. That is called `include(tests)` from our main CMake file

Follow up to #61 #2

**Comment by ctrl-z-9000-times** [comment]
I like the idea of splitting up & organizing the cmake file. currently it does everything in one big file. From what ive seen in the past i think that many cmake files is the norm.

**Comment by dkeeney** [comment]
We are in the process of removing a lot of the prerequisites so there will
be a LOT less stuff the CMake files have to do.   And we will be splitting
out the Python interface into a separate file. I suggest that we wait and
see what it looks like at that point.

**Comment by breznak** [comment]
Closing as implemented somewhere in #157 and before, pybind PRs. 
Tests now have their own src/tests/CMakeLists file. 
separating them over to /bindings/ would probably be an overkill, as we always want to run tests (for core and built modules)
