### ISSUE TITLE
Unable to install htm.core on MacOS -- CMake Error during installation

### ISSUE THREAD

**Issue by bisalgt** [htm-community/nupic.cpp#966]
Inside the Conda environment, the python version is 3.9.7. I had cloned the htm.core repo and after getting inside the htm directory  , I tried to run python setup.py install. While doing so, I am facing a CMake Error and unable to figure out what to do next. I have also attached an image. Please let me know the possible solutions
<img width="1439" alt="htm core error" src="https://user-images.githubusercontent.com/43409127/152180247-05fa74e2-e49c-4149-8bd5-79c167ff89c0.png">

<img width="1439" alt="htm core error 2" src="https://user-images.githubusercontent.com/43409127/152180278-989d66b2-a452-42a6-8a5d-b49b20dd5469.png">

**Comment by bisalgt** [comment]
After creating a folder[include/python3.9] inside /opt/anaconda3/python.app/Contents/. The error was gone.
But still there is some error subprocess.CalledProcessError. I am unable to use htm inside the python environment.

I have also attache image for the findings below.
<img width="1439" alt="subprocess Called processerror" src="https://user-images.githubusercontent.com/43409127/152189533-3bbe1f25-a6c0-4ba9-a5ab-f1aa3f379e53.png">

**Comment by dkeeney** [comment]
I don't have a Mac and I don't have Anacondra to try to reproduce this.
On Windows 11, with Python 3.9.6 (from python.org), a fresh clone builds just fine.

CMake cache's things between builds and you mentioned that you restarted the build. It is possible that something in the cache was confused.  So, try deleting the entire 'build' directory and run the build again.
If that does not work then I will attempt to get an Anacondra python and try to reproduce the error.

**Comment by ctrl-z-9000-times** [comment]
The error message says you're missing "Python.h" which IIRC you need to install from the "python3-dev" package.
Like: `sudo apt-get install python3-dev`

**Comment by bisalgt** [comment]
@dkeeney  Thank you so much. Yes I had deleted the build folder. I am trying to install it but no luck.

**Comment by bisalgt** [comment]
@ctrl-z-9000-times Since I am using Conda environment in MacOs, I cannot run sudo apt-get install python3-dev. I am trying to find its alternative for macOS. Thank you so much.

**Comment by bisalgt** [comment]
I did brew install python. All the dependencies were installed on my system with this line.And now the error is gone. Setup is complete. Thanks for the help @dkeeney @ctrl-z-9000-times
